- BlueComponents.js
- entropy.js
- package-lock.json
- screen/send/details.js
- screen/settings/about.js
- screen/wallets/details.js
- screen/wallets/transactions.js
@marcosrdz pls review. Its based on your `smalluifixes` branch, but keeps expo 30
> FIX: better android support

- screen/receive/details.js
Used `bip21` library to encode address to BIP21 format.
> QR code content follows BIP21

- HDWallet.test.js
- class/abstract-hd-wallet.js
- class/hd-legacy-breadwallet-wallet.js
- class/hd-legacy-p2pkh-wallet.js
- class/hd-segwit-p2sh-wallet.js
- models/signer.js
- screen/send/details.js
- screen/wallets/scanQrWif.js
re https://github.com/BlueWallet/BlueWallet/pull/161
> Pajasevi spend bip44

- MainBottomTabs.js
- loc/en.js
- loc/es.js
- loc/pt_BR.js
- loc/pt_PT.js
- loc/ru.js
- loc/ua.js
- screen/wallets/details.js
- screen/wallets/xpub.js
Added option to show wallet XPUB (YPUB) for HD wallets. Nothing fancy.
Closes #135
> Feature: Ability to show wallet XPUB in options

- loc/en.js
> Typo under "import"

- class/hd-legacy-breadwallet-wallet.js
- class/hd-legacy-p2pkh-wallet.js
- class/hd-segwit-p2sh-wallet.js
I refactored the HD wallets, mainly Segwit P2SH, to derive addresses from XPUB every time.
There was a lot of repeated code which is now deleted so it is more readable and prone to errors.
Next step will be using Typescript.
> Refactor: HD wallets address derivation

- screen/lnd/lndViewInvoice.js
added scroll view and increased qr code size.
it looks a bit ugly with scroll, but thats the only way to fit all this data and big enough QR
> FIX: too small QR on ln receive invoice (closes #235)

- loc/cs_CZ.js
- loc/da_DK.js
- loc/de_DE.js
- loc/en.js
- loc/es.js
- loc/fr_FR.js
- loc/hr_HR.js
- loc/jp_JP.js
- loc/nl_NL.js
- loc/pt_BR.js
- loc/pt_PT.js
- loc/ru.js
- loc/th_TH.js
- loc/ua.js
- screen/receive/receiveAmount.js
- screen/settings/language.js
- screen/settings/lightningSettings.js
- screen/settings/settings.js
- Fix some dutch translation
- Move some hardcoded language to localization
> Localization fixes

- loc/jp_JP.js
Adjusted wording and the number of words in order to fit to the display area in the app.
> Made minor Japanese wording adjustment

- models/fiatUnit.js
If I'm missing anything let me know.
> Adds NZD as a currency

- screen/send/details.js
@marcosrdz if you have time test this a bit
> FIX: Impossible to scan bech32 QR invoice with a specific amount

- MainBottomTabs.js
- class/abstract-wallet.js
- class/lightning-custodian-wallet.js
- models/bitcoinUnits.js
- package-lock.json
- screen/lnd/manageFunds.js
- screen/lnd/scanLndInvoice.js
- screen/send/details.js
- screen/wallets/selectWallet.js
ADD: If providing an LND address in BTC send screen, throw an error.
ADD: Chain type in order to determine what type of wallet has been selected.
> ADD: Switch Lightning wallets on send screen.

- App.js
- BlueComponents.js
- Privacy.js
- package-lock.json
- package.json
- screen/send/details.js
ADD: Clipboard detection on app state change to foreground
OPS: Upgrade to RN 58.6 due to various important fixes
> FIX: Create button was difficult to press on android.

- screen/lnd/scanLndInvoice.js
- screen/wallets/export.js
- screen/wallets/transactions.js
ADD: Haptic feedbacks on error alerts
> FIX: UI fixes for  transactions list

- loc/index.js
- loc/it.js
- screen/send/details.js
> FIX: Fixed an isse when inserting an address after amount.

- package.json
Due to a very important Android related fix (https://github.com/facebook/react-native/commit/d6bca9723e6226688ec1bb3301d7ce39a17f79e3)
> Update RN to 0.59.4

- screen/receive/details.js
Users complaining they couldn't read the qr code, tested with different variations, this seems to work
> improve quality of qr code

- BlueComponents.js
- loc/cs_CZ.js
- loc/da_DK.js
- loc/de_DE.js
- loc/el.js
- loc/en.js
- loc/es.js
- loc/fi_FI.js
- loc/fr_FR.js
- loc/hr_HR.js
- loc/hu_HU.js
- loc/id_ID.js
- loc/it.js
- loc/jp_JP.js
- loc/nb_NO.js
- loc/nl_NL.js
- loc/pt_BR.js
- loc/pt_PT.js
- loc/ru.js
- loc/sv_SE.js
- loc/th_TH.js
- loc/tr_TR.js
- loc/ua.js
- loc/zh_cn.js
- package.json
- screen/lnd/lndCreateInvoice.js
Spec: https://github.com/btcontract/lnurl-rfc/blob/master/spec.md#3-withdrawing-funds-from-a-service.
It's specially useful in these days post 0-sat invoice exploit.
How it works on lightning-wallet.com, for reference: ![](https://user-images.githubusercontent.com/1653275/61960649-3d512d80-af9c-11e9-97d4-b0ba00d3043d.gif)
> Add support for LNURL withdraws

- screen/receive/details.js
- screen/wallets/transactions.js
Brings address position to near the QR code instead the bottom of the page
> fix address position

- screen/send/details.js
- screen/wallets/transactions.js
Fix margins between elements, and makes both elements tapable
> fix wallet selector on send view

- BlueApp.js
- index.js
@marcosrdz can you confirm that this new place where I put INIT _always_ get executed? Migrated, non-migrated, doesnt matter..?
> FIX: analytics INIT event a bit later in startup

- BlueComponents.js
- screen/wallets/import.js
> FIX: Seed phrase import issues

- screen/wallets/details.js
> FIX: Add warning to or restrict delete wallet option when it has balance

- App.js
- screen/lnd/lndCreateInvoice.js
> handle LNURL clicks

- BlueComponents.js
- currency.js
- ios/Podfile
- ios/Podfile.lock
- models/bitcoinTransactionInfo.js
- models/signer.js
- screen/send/confirm.js
- screen/send/create.js
- screen/send/details.js
- screen/send/success.js
> WIP: Batch UI

- MainBottomTabs.js
- class/abstract-wallet.js
- class/onAppLaunch.js
- screen/settings/defaultView.js
- screen/settings/settings.js
- screen/wallets/list.js
- screen/wallets/selectWallet.js
- screen/wallets/transactions.js
> ADD: Default into wallet

- BlueComponents.js
- loc/index.js
- screen/wallets/transactions.js
> FIX: Time shown for top-most transaction

- BlueComponents.js
- MainBottomTabs.js
- class/abstract-hd-wallet.js
- class/hd-segwit-bech32-wallet.js
- class/watch-only-wallet.js
- screen/receive/details.js
- screen/send/details.js
- screen/send/psbtWithHardwareWallet.js
- screen/wallets/details.js
- screen/wallets/transactions.js
- tests/integration/WatchOnlyWallet.test.js
- tests/integration/hd-segwit-bech32-wallet.test.js
> WIP: low-level code for HW wallet PSBT integration

- ios/Podfile.lock
- package-lock.json
- package.json
- screen/lnd/lndViewAdditionalInvoiceInformation.js
- screen/lnd/lndViewInvoice.js
- screen/receive/details.js
- screen/wallets/export.js
- screen/wallets/xpub.js
about:blank crashes the web view @Overtorment
> DEL: Remove react-native-system-setting

- ios/fastlane/metadata/en-US/release_notes.txt
- loc/ZAR_Afr.js
- loc/ZAR_Xho.js
- loc/cs_CZ.js
- loc/da_DK.js
- loc/de_DE.js
- loc/el.js
- loc/en.js
- loc/es.js
- loc/fi_FI.js
- loc/fr_FR.js
- loc/hr_HR.js
- loc/hu_HU.js
- loc/id_ID.js
- loc/it.js
- loc/nb_NO.js
- loc/nl_NL.js
- loc/pt_BR.js
- loc/pt_PT.js
- loc/ru.js
- loc/sv_SE.js
- loc/th_TH.js
- loc/tr_TR.js
- loc/ua.js
- loc/vi_VN.js
- loc/zh_cn.js
- loc/zh_tw.js
- screen/receive/details.js
- screen/wallets/pleaseBackup.js
- screen/wallets/transactions.js
Follows the floating layout, avoiding overriding words when these are bigger than the column space, add badges to the background to facilitate reading
> Redone pleasebackup view following the mockup

- screen/lnd/lndViewInvoice.js
Add memo and value to invoice details screen. When is a receive payment, there's no "description" field.
> Add memo and value to invoice details screen

- App.js
- BlueComponents.js
- analytics.js
- class/app-storage.js
- index.js
- ios/fastlane/metadata/en-US/release_notes.txt
- package-lock.json
- package.json
- screen/wallets/list.js
> Improv analytics

- android/app/src/main/AndroidManifest.xml
- class/hd-segwit-bech32-wallet.js
- screen/send/details.js
> ADD: Toggle for RBF

- screen/lnd/lndCreateInvoice.js
> FIX: Scan to receive is more visible

- App.js
- MainBottomTabs.js
- screen/wallets/selectWallet.js
If both schemas are detected, user is given the option to select a wallet.
> ADD: Handle clipboard content with both bitcoin: and lightning:

- screen/wallets/add.js
Scrollview for smaller screens.
> FIX: Wallet type selecion clipping on advanced mode

- BlueComponents.js
- class/abstract-wallet.js
- loc/es.js
- screen/lnd/lndCreateInvoice.js
- screen/receive/details.js
- screen/wallets/export.js
- screen/wallets/import.js
- screen/wallets/transactions.js
> ADD: Ask user if they have backed up their seed phrase

- README.md
> Update Android build instructions

- README.md
refer here for more information:
https://github.com/BlueWallet/BlueWallet/issues/802
> updating instructions for console compilation

- screen/wallets/hodlHodl.js
- screen/wallets/list.js
- screen/wallets/transactions.js
If this is not the most elegant way to do this, let me know
> align margin on tx list

- screen/wallets/list.js
with bounce on ViemPager component the background should be white to look less weird
> background white

- screen/settings/electrumSettings.js
- screen/settings/settings.js
Visual changes on the Electrum view. At the moment it is missing a listener to provide live updates, the user has to kill the app to see any changes.
> Electrum bluefy

- MainBottomTabs.js
- class/handoff.js
- ios/Podfile.lock
- loc/en.js
- screen/settings/GeneralSettings.js
- screen/settings/NetworkSettings.js
- screen/settings/defaultView.js
- screen/settings/settings.js
- screen/transactions/details.js
- screen/transactions/transactionStatus.js
- screen/wallets/transactions.js
> ADD: General Settings

- android/app/build.gradle
- ios/BlueWallet/Info.plist
- ios/BlueWalletWatch Extension/Info.plist
- ios/BlueWalletWatch/Info.plist
- ios/TodayExtension/Info.plist
- ios/fastlane/metadata/copyright.txt
- package-lock.json
- package.json
- screen/selftest.js
- screen/settings/electrumSettings.js
- tests/e2e/selftest.spec.js
> TST: selftest improvements

- ios/Podfile.lock
- package-lock.json
- package.json
- screen/wallets/marketplace.js
> OPS: Update modal

- screen/settings/currency.js
> rewrite currency screen using functional components

- screen/ActionSheet.android.js
- screen/ActionSheet.ios.js
- screen/wallets/transactions.js
> ADD: Long Press on Send. More optins to come

- loc/en.js
- screen/lnd/lndViewInvoice.js
- screen/wallets/transactions.js
Reverts BlueWallet/BlueWallet#1027
> Revert "FIX: Remove 3rd button from lightning wallets top"

- ios/fastlane/metadata/en-US/description.txt
- ios/fastlane/metadata/en-US/keywords.txt
Add new features to the description, mainly to improve ASO rank. Also let's see if fastlane is still working
> OPS: New iOS description

- class/app-storage.js
- class/hd-segwit-electrum-seed-p2wpkh-wallet.js
- class/index.js
- class/walletGradient.js
- class/walletImport.js
- tests/unit/hd-legacy-electrum-seed-p2pkh-wallet.test.js
- tests/unit/hd-segwit-electrum-seed-p2wpkh-wallet.test.js
This branch is based on #1046 
So ideally we should merge #1046 first.
> Add electrum segwit

- BlueComponents.js
> FIX: Tx list with elements upgrade

- loc/ZAR_Afr.js
- loc/ZAR_Xho.js
- loc/cs_CZ.js
- loc/da_DK.js
- loc/de_DE.js
- loc/el.js
- loc/en.js
- loc/es.js
- loc/fi_FI.js
- loc/fr_FR.js
- loc/hr_HR.js
- loc/hu_HU.js
- loc/id_ID.js
- loc/it.js
- loc/jp_JP.js
- loc/nb_NO.js
- loc/nl_NL.js
- loc/pt_BR.js
- loc/pt_PT.js
- loc/ru.js
- loc/sv_SE.js
- loc/th_TH.js
- loc/tr_TR.js
- loc/ua.js
- loc/vi_VN.js
- loc/zh_cn.js
- loc/zh_tw.js
- screen/wallets/details.js
Fixes hardcoded strings in screen/wallets/details.js:
'connect to'
'advanced'
'Use with hardware wallet'
Creates new entries on all loc files:
loc.wallets.details.connected_to
loc.wallets.details.advanced
loc.wallets.details.use_with_hardware_wallet
> Add locs to details

- screen/wallets/list.js
- screen/wallets/transactions.js
> REF: Make statusbar on android the wallet color

- screen/send/ScanQRCode.js
- screen/wallets/transactions.js
Fixing #1160
because componentDidMount is an async function, addListener was fired too soon.
I've fixed it by moving before awat
Also, I've added style change of StatusBar in ScanQRCode screen as described in
https://github.com/BlueWallet/BlueWallet/issues/1160#issuecomment-636449188
> FIX: listen focus events correctly on wallet transactions screen

- BlueComponents.js
> FIX: scan button style for RU language

- screen/lnd/browser.js
- screen/lnd/lndCreateInvoice.js
- screen/lnd/scanLndInvoice.js
- screen/receive/aztecoRedeem.js
- screen/receive/details.js
- screen/send/ScanQRCode.js
- screen/send/details.js
- screen/transactions/details.js
- screen/wallets/add.js
- screen/wallets/buyBitcoin.js
- screen/wallets/details.js
- screen/wallets/export.js
- screen/wallets/import.js
- screen/wallets/reorderWallets.js
- screen/wallets/selectWallet.js
- screen/wallets/transactions.js
- screen/wallets/xpub.js
> FIX: StatusBar wasn't visible when modals opened

- screen/wallets/provideEntropy.js
- tests/unit/provide-entropy.test.js
D16 should provide 2 bits not 3
> FIX: provide entropy for D20

- blue_modules/notifications.js
- screen/lnd/lndViewInvoice.js
- screen/receive/details.js
Refactored for smooth transition as suggested by: https://reactnavigation.org/docs/use-focus-effect/#delaying-effect-until-transition-finishes
> REF: Use useFocusEffect on Receive screen

- blue_modules/notifications.js
- screen/lnd/lndViewInvoice.js
- screen/receive/details.js
Reverts BlueWallet/BlueWallet#1372
> Revert "REF: Use useFocusEffect on Receive screen"

- BlueApp.js
- blue_modules/notifications.js
- screen/lnd/lndViewInvoice.js
- screen/receive/details.js
> Receivecallback

- LICENSE
Not even in the right epoch 🤦 😛
> Update LICENSE copyright date

- BlueComponents.js
- screen/wallets/add.js
Reverts BlueWallet/BlueWallet#1357
> Revert "REF: Add Wallet Hooks"

- App.js
- screen/receive/details.js
- screen/send/details.js
- screen/wallets/hodlHodl.js
- screen/wallets/hodlHodlMyContracts.js
- screen/wallets/transactions.js
Without this, the modal shadow doesnt cover the whole screen on macOS
> ADD: Modal Device Height props for macOS

- README.md
Warn users about values in curly brackets to prevent errors like https://github.com/BlueWallet/BlueWallet/pull/1495
> FIX: readme explane localization vars

- blue_modules/notifications.js
Catalyst reports itself as emulator and as iOS..causing notifications to not be enabled on desktop.
> DEL: Remove Emulator check

- ios/fastlane/metadata/fr_FR/keywords.txt
> FIX: remove fastlane metadata fr_FR lang

- screen/wallets/transactions.js
broken in https://github.com/BlueWallet/BlueWallet/pull/1596
> FIX: broken LN -> manage funds -> refill

- screen/send/details.js
> FIX: update recalculate fee on send screen with custom sat/byte fee rate

- BlueComponents.js
- screen/transactions/CPFP.js
fixing #1800 
Also, I've added `<KeyboardAvoidingView` to prevent overlapping of textinput
> FIX: set default fee in CPFP/RBF fee-selection component

- BlueComponents.js
> FIX: add margin for RTL languages

- README.md
fix for pod-install command, current podinstall command returns 404
> DOC: fix command for running ios

- blue_modules/fs.js
- screen/send/ScanQRCode.js
gentlemen, from now on lets isolate file operations in `blue_modules/fs`
> REF: showing dialog and opening psbt files

- BlueComponents.js
- class/camera.js
- class/hd-segwit-bech32-transaction.js
- class/index.js
- class/wallets/hd-legacy-electrum-seed-p2pkh-wallet.js
- class/wallets/hd-segwit-electrum-seed-p2wpkh-wallet.js
- screen/send/ScanQRCode.js
- screen/transactions/details.js
- screen/wallets/import.js
- screen/wallets/list.js
* a few require cycle errors
* move `navigation.setParams` from component constructor to `componentDidMount`
> FIX: a few react errors

- blue_modules/prompt.js
> REF: show numeric keyboard when ask for numbers in prompt

- models/fiatUnit.js
> ADD: Philippines Peso currency

- screen/settings/lightningSettings.js
https://github.com/BlueWallet/BlueWallet/issues/1193
> ADD: import LNDHub from QR

- ios/Podfile.lock
- package-lock.json
- package.json
> OPS: Notification package

- loc/en.json
Kind of difficult to localize this expression, I propose simplify it for its dumbest form.
> REF: Simplify Co-sign QR-airgapped transaction

- loc/en.json
- screen/send/details.js
- screen/wallets/export.js
> ADD: warning text on backup screen

- screen/send/psbtMultisig.js
> FIX:  Multisig Confirm button is too small #2254

- tests/e2e/bluewallet.spec.js
I made sure the bluewallet.spec.js is compliant with the changes in punctuation marks made in previous PRs.
> REF: Updating bluewallet.spec

- loc/en.json
“Insert Transaction Hex”
“Insert Derivation Path”
>  REF: Correcting two “Input” instances

- loc/pt_br.json
> Fixes misspelling

- loc/index.js
- screen/transactions/details.js
> FIX: use dayjs localizedFormat plugin to render tx time

- loc/en.json
- screen/send/coinControl.js
- show number of confirmations in Output Modal
- allow to select a few outputs and Freeze/Unfreeze/Use them
> ADD: CoinControl multiselect

- screen/lnd/scanLndInvoice.js
> FIX: alert no LN wallet

- screen/send/coinControl.js
> FIX: coincontrol no connection on fetchUtxo()

- ios/Podfile.lock
- package-lock.json
- package.json
> OPS: Package Update

- components/WalletsCarousel.js
- screen/wallets/reorderWallets.js
closes https://github.com/BlueWallet/BlueWallet/issues/2201
> FIX: 'Few seconds ago' -> 'pending'

- README.md
Broken image paths with the new website deploy
> Fix image paths

- class/wallets/multisig-hd-wallet.js
- screen/wallets/addMultisig.js
- screen/wallets/addMultisigStep2.js
https://github.com/Coldcard/firmware/blob/65cd37738bd1720ce0abbb4bce5950ce1ce7b007/releases/ChangeLog.md
> REF: better support of coldcard's incorrect 'p2sh-p2wsh'

- screen/send/details.js
Closes #1799
If balance is not enough even for Slow option, 1 sat/byte will be used
https://user-images.githubusercontent.com/155891/106481874-ef38b680-64bd-11eb-885f-b18121087599.mov
> FIX: set fee to lower value if balance is not enought

- BlueComponents.js
- components/TooltipMenu.android.js
- components/TooltipMenu.ios.js
- components/TooltipMenu.js
- ios/BlueWallet.xcodeproj/xcshareddata/xcschemes/BlueWalletWatch (Notification).xcscheme
- screen/transactions/details.js
> ADD: Copying Block Explorer Link #2597

- screen/receive/details.js
Lets u print/save/share QRCode image.
> ADD: Tap and hold to Share QRCode image

- ios/BlueWalletWatch Extension/ComplicationController.swift
- ios/BlueWalletWatch Extension/Info.plist
- ios/WalletInformationWidget/Widgets/Shared/WidgetDataStore.swift
> ADD: graphicRectangular complication

- screen/wallets/buyBitcoin.js
- tests/unit/segwit-p2sh-wallet.test.js
@marcosrdz this context biz is broken on that screen, can you pls glance if there are any other issues?
> FIX: broken buyBitcoin button for some wallets (closes #2684)

- screen/send/details.js
- tests/e2e/bluewallet.spec.js
closes #1904
https://user-images.githubusercontent.com/155891/109118198-12205880-7754-11eb-8a80-5e7a3c337fca.mov
> TST: batch send test

- BlueComponents.js
- blue_modules/fs.js
- components/FloatButtons.js
- components/SquareButton.js
- components/WalletsCarousel.js
- screen/send/isItMyAddress.js
- screen/send/psbtMultisigQRCode.js
- screen/send/psbtWithHardwareWallet.js
- screen/wallets/addMultisigStep2.js
- screen/wallets/details.js
- screen/wallets/list.js
- screen/wallets/transactions.js
- screen/wallets/viewEditMultisigCosigners.js
- tests/e2e/bluewallet.spec.js
instead of at the center, it anchors to the corresponding button
> REF: Use actionsheet anchor property button ipad options

- screen/send/broadcast.js
- screen/settings/GeneralSettings.js
- screen/settings/NetworkSettings.js
- screen/settings/SettingsPrivacy.js
- screen/settings/electrumSettings.js
- screen/settings/lightningSettings.js
- screen/settings/notificationSettings.js
- screen/settings/settings.js
- tests/e2e/bluewallet.spec.js
> TST: settings screens test

- App.js
- screen/wallets/list.js
Adds native style for android StatusBar in light and dark themes, on the initial screen and list screen.
> REF: Status Bar on android with native style

- screen/send/details.js
- tests/e2e/bluewallet.spec.js
- Fixes white screen when remove last of 3 recipients on android
- Add key for addresses array so that FlatList shows correct animations
- Fixes track of current recipient index in Component store. Recepient remove now correctly removes active element, not the last one.
closes #2362
> FIX: recipients index

- class/wallet-gradient.js
@marcosrdz check if it is less blinding
> FIX: Bring down the color brightness

- loc/en.json
- screen/send/details.js
- tests/e2e/bluewallet.spec.js
- tests/integration/hd-segwit-p2sh-wallet.test.js
> ADD: Use Full Balance and Multiple recipients

- Navigation.js
- class/wallets/lightning-custodian-wallet.js
- class/wallets/watch-only-wallet.js
- components/FloatButtons.js
- loc/en.json
- screen/wallets/details.js
- screen/wallets/signVerify.js
This is for upcoming #990
cc @jaonoctus 
Screen expects  `address` and `walletID` from route params
> ADD: SignVerify screen

- class/wallets/abstract-hd-electrum-wallet.js
- class/wallets/abstract-wallet.js
- class/wallets/hd-aezeed-wallet.js
- class/wallets/hd-legacy-breadwallet-wallet.js
- class/wallets/hd-legacy-electrum-seed-p2pkh-wallet.js
- class/wallets/hd-legacy-p2pkh-wallet.js
- class/wallets/hd-segwit-bech32-wallet.js
- class/wallets/hd-segwit-electrum-seed-p2wpkh-wallet.js
- class/wallets/hd-segwit-p2sh-wallet.js
- class/wallets/multisig-hd-wallet.js
- class/wallets/watch-only-wallet.js
- screen/wallets/details.js
- tests/unit/hd-legacy-wallet.test.js
- tests/unit/hd-segwit-bech32-wallet.test.js
- tests/unit/hd-segwit-p2sh-wallet.test.js
- fingerprint shown for HDLegacyP2PKHWallet, HDSegwitBech32Wallet, HDSegwitP2SHWallet and for WatchOnly+zpub wallets
- derivation path shown for all HD wallets
closes #2823
> ADD: show fingerprint and derivation path for HD wallets

- screen/send/details.js
- tests/e2e/bluewallet.spec.js
> FIX: address input qrcode denomination reset

- screen/lnd/lndViewInvoice.js
For some reason the `<scrollview>` element is removing the flex layout logic, bottom elements are on the center, etc.
> REF: Fix layout on invoice view

- Navigation.js
- components/addresses/AddressItem.js
- components/addresses/AddressTypeBadge.js
- components/themes.js
- loc/en.json
- screen/wallets/addresses.js
- screen/wallets/details.js
- tests/unit/addresses.test.js
> ADD: Hierarchy Navigator Screen

- ios/Podfile.lock
- package-lock.json
- package.json
- screen/settings/about.js
this will allow us to ask users to copy their sentry id so we can paste it in sentry UI to check whats wrong.
cc @ncoelho 
PS.  @marcosrdz you might need to do your pod magic on this
> REF: better Sentry integration

- class/wallets/watch-only-wallet.js
- screen/send/details.js
- screen/wallets/details.js
- screen/wallets/transactions.js
- tests/unit/watch-only-wallet.test.js
I've successfully created psbt using `xpub` and signed it with `HDLegacyP2PKHWallet` wallet
> ADD: Allow create PSBT for all HD watch-only wallets

- loc/en.json
- screen/wallets/pleaseBackup.js
> REF: Align elements on backup view

- screen/receive/details.js
> REF: Align Receive view elements

- ios/Podfile.lock
- screen/wallets/addMultisigStep2.js
Must've been code leftover from a copy paste. Doesnt belong there.
> DEL: Remove tooltip as its not needed on multisig create screen.

- class/wallets/abstract-hd-electrum-wallet.js
- class/wallets/legacy-wallet.js
- tests/integration/hd-segwit-bech32-wallet.test.js
> FIX: Check Bech32 uppercase address

- BlueApp.js
- class/app-storage.js
- package-lock.json
- package.json
- tests/setup.js
even tho i cant reproduce race condition on keystore write, I think its a good idea to add protection against it
> REF: storage write

- package-lock.json
- package.json
Windows and native macOS support
> OPS: Update package

- components/addresses/AddressItem.js
- components/addresses/AddressTypeBadge.js
- components/addresses/AddressTypeTabs.js
- loc/ar.json
- loc/cs_cz.json
- loc/cy.json
- loc/de_de.json
- loc/en.json
- loc/es_419.json
- loc/fa.json
- loc/fr_fr.json
- loc/pl.json
- loc/pt_br.json
- loc/sl_SI.json
- screen/wallets/addresses.js
- tests/unit/addresses.test.js
> REF: Hierarchy navigator screen

- ios/Widgets/Shared/WidgetAPI.swift
- models/fiatUnit.js
- models/fiatUnit.json
- tests/integration/Currency.test.js
> ADD: IRR currency 

- WatchConnectivity.ios.js
- screen/receive/details.js
- screen/wallets/aopp.js
Fixes https://github.com/BlueWallet/BlueWallet/issues/696
> FIX: remove checks before invoking getAddressAsync

- class/wallet-import.js
- class/wallets/abstract-wallet.js
- screen/send/ScanQRCode.js
- screen/wallets/import.js
- tests/unit/fixtures/skeleton-cobo.txt
- tests/unit/watch-only-wallet.test.js
Closes https://github.com/BlueWallet/BlueWallet/issues/3371
> Display derivation path for HD watch-only wallets

- blue_modules/BlueElectrum.js
- blue_modules/environment.js
- class/wallets/lightning-custodian-wallet.js
- screen/send/confirm.js
- screen/settings/NetworkSettings.js
- screen/settings/electrumSettings.js
- screen/settings/lightningSettings.js
- screen/settings/torSettings.js
- scripts/maccatalystpatches/applypatchesformaccatalyst.sh
- tests/setup.js
Removes the need to manual code adjustments on platforms that aren't compatible with react-native-tor
> ADD: isTorCapable

- BlueComponents.js
- class/wallet-import.js
- loc/en.json
- screen/wallets/export.js
- screen/wallets/import.js
- tests/e2e/bluewallet.spec.js
- tests/integration/import.test.js
- tests/unit/hd-aezeed.test.js
It uses alert with input to ask for a passphrase
Currently it works with standard HD wallets + aezeed + slip39
https://user-images.githubusercontent.com/155891/126078571-5bd40b78-367f-45ff-9825-8b3637447b28.mp4
> ADD: UI for import wallet with passphrase

- README.md
- blue_modules/bip38/README.md
- blue_modules/scryptsy/README.md
- ios/fastlane/metadata/ar-SA/privacy_url.txt
- ios/fastlane/metadata/da/privacy_url.txt
- ios/fastlane/metadata/de-DE/privacy_url.txt
- ios/fastlane/metadata/en-US/privacy_url.txt
- ios/fastlane/metadata/es-ES/privacy_url.txt
- ios/fastlane/metadata/es-MX/privacy_url.txt
- ios/fastlane/metadata/fi/privacy_url.txt
- ios/fastlane/metadata/fr-FR/privacy_url.txt
- ios/fastlane/metadata/he/privacy_url.txt
- ios/fastlane/metadata/hu/privacy_url.txt
- ios/fastlane/metadata/it/privacy_url.txt
- ios/fastlane/metadata/nl-NL/privacy_url.txt
- ios/fastlane/metadata/no/privacy_url.txt
- ios/fastlane/metadata/pl/privacy_url.txt
- ios/fastlane/metadata/pt-BR/privacy_url.txt
- ios/fastlane/metadata/pt-PT/privacy_url.txt
- ios/fastlane/metadata/ro/privacy_url.txt
- ios/fastlane/metadata/ru/privacy_url.txt
- ios/fastlane/metadata/sv/privacy_url.txt
- ios/fastlane/metadata/zh-Hans/privacy_url.txt
Closes https://github.com/BlueWallet/BlueWallet/issues/3083
> Replace http uris/links with https

- class/wallet-import.js
- tests/integration/import.test.js
Same as #3406 but for wallets with electrum seed
> ADD: UI for import electrum wallet with passphrase

- screen/send/details.js
> FIX: Disable slower fees if they match faster fee

- screen/send/details.js
If Send screen is open, UI would not update with new deep linked data. 
With this change, the current index data will update.
> FIX: Update UI for Send screen if new deeplink data is available

- class/wallets/abstract-hd-wallet.ts
- tests/integration/import.test.js
Closes https://github.com/BlueWallet/BlueWallet/issues/3476
> Add support for BIP39 truncated wordlist

- components/AddressInput.js
- screen/send/confirm.js
> REF: Update Details button to match design

- Navigation.js
> FIX: AOPP select wallet

- loc/en.json
- screen/wallets/importDiscovery.js
> ADD: show message if no wallets has been found during the import

- class/deeplink-schema-match.js
- screen/wallets/buyBitcoin.js
- tests/unit/deeplink-schema-match.test.js
test safello deeplink is on https://bluewallet.io/testpage/
> FIX: safello & default currency for buyBitcoin

- components/themes.ts
- screen/settings/settings.js
- screen/wallets/add.js
- screen/wallets/addMultisig.js
- screen/wallets/addMultisigHelp.js
- screen/wallets/addMultisigStep2.js
- screen/wallets/import.js
- screen/wallets/importDiscovery.js
- screen/wallets/list.js
- screen/wallets/pleaseBackup.js
- screen/wallets/pleaseBackupLNDHub.js
- screen/wallets/pleaseBackupLdk.js
No need to specify StatusBar on every screen. Only on the main ones, it's children will follow the parent's barStyle
> FIX: Statusbar barstyle

- ios/BlueWalletWatch Extension/Objects/Handoff.swift
- ios/BlueWalletWatch Extension/ReceiveInterfaceController.swift
- ios/BlueWalletWatch Extension/ViewQRCodefaceController.swift
- ios/BlueWalletWatch Extension/WalletDetailsInterfaceController.swift
- ios/BlueWalletWatch/Base.lproj/Interface.storyboard
Apple being Apple changed watchOS guidelines
> FIX: Use buttons rather than menu items due to watchOS changes

- components/TooltipMenu.android.js
- components/TooltipMenu.ios.js
- components/TransactionListItem.js
- components/TransactionsNavigationHeader.js
- screen/send/details.js
Used to be limited to 1 submenu
> REF: Allow multiple submenus

- blue_modules/currency.js
- screen/lnd/lnurlPay.js
convert lnurl amount from sats to BTC or local_currency if needed 
closes #3842
> FIX: lnPayURL scan wallet currency in BTC or local currency

- components/AmountInput.js
- loc/en.json
> ADD: Rate last updated date

- screen/wallets/importCustomDerivationPath.js
> FIX: import custom derivation path with passphrase

- tests/integration/import.test.js
- tests/unit/bip38.test.js
> TST: fix timeouts on some tests

- class/wallets/legacy-wallet.ts
- screen/send/details.js
- tests/integration/legacy-wallet.test.js
- tests/unit/legacy-wallet.test.js
@junderw can you pls take a look
> FIX: reject unknown segwit versions as invalid address

- class/wallets/slip39-wallets.js
- package-lock.json
- tests/unit/slip39-wallets.test.js
Needs to be https://github.com/BlueWallet/slip39-js/pull/1 merged at first
closes #4286
> ADD: support truncated words during slip39 wallet import

- tests/integration/aopp.test.js
Instead of fragile tests that depends on external server, run local http server during tests to receive callbacks
> TST: aopp tests with local http server

- loc/en.json
- screen/send/coinControl.js
https://user-images.githubusercontent.com/155891/150766618-97c1f978-93a1-43dd-be7b-fc215a39c0a9.mp4
closes #4404
> ADD: show selected coins summary on CoinControl screen

- android/app/build.gradle
> OPS: Unable to create aab (android bundle) #4235

- class/wallet-import.js
- tests/integration/import.test.js
> FIX: allow user to choose wallet type when importing empty WIF

- blue_modules/bip39.js
- class/wallets/abstract-hd-wallet.ts
- tests/integration/import.test.js
- tests/unit/hd-legacy-breadwallet.test.js
- tests/unit/hd-segwit-bech32-wallet.test.js
This changes only recovering.
I didn't touch multisig implementation. 
closes #4649 #4598
> ADD: import bip39 multilang mnemonics

- ios/BlueWallet.xcodeproj/project.pbxproj
- ios/Podfile
- ios/Podfile.lock
> DEL: iOS Hermes

- LICENSE
- RELEASE.md
- ios/fastlane/metadata/copyright.txt
- package-lock.json
- package.json
- screen/settings/licensing.js
> Minor fixes

- blue_modules/BlueElectrum.d.ts
- blue_modules/BlueElectrum.js
- class/index.js
- class/wallets/taproot-wallet.js
- tests/integration/BlueElectrum.test.js
- tests/unit/taproot-wallet.test.js
@junderw can you please take a look? Thanks
> FIX: better support parsing taproot addresses from Electrum (rel #4749)

- screen/wallets/addresses.js
> ADD: Search on addresses screen #4260

- package-lock.json
- package.json
forked 2 localize repos under our org
> REF: react-localize dep cleanup

- package-lock.json
- package.json
Reverts BlueWallet/BlueWallet#5204
> Revert "Update dependency react-native-windows to v0.70.7"

- loc/languages.ts
Polski is singular, Polskie is plural
> Use "Polski" for Polish Language

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/io/bluewallet/bluewallet/MainApplication.java
- android/gradle.properties
as per install docs, we dont need those lines..?
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation
> REF: attempt to cleanuop & speedup android native

- class/app-storage.js
> FIX: secure keystore keys should not leave device

- package-lock.json
- package.json
Reverts BlueWallet/BlueWallet#5367
> Revert "Update dependency react-native to v0.71.4"

- blue_modules/storage-context.js
- screen/settings/GeneralSettings.js
> FIX: setIsAdvancedModeEnabled

- screen/wallets/transactions.js
It was refetching by simply changing the unit
> FIX: Only attempt refetch is walletID changed

- screen/settings/currency.js
> ADD: Search currency

- .github/workflows/build-release-apk.yml
Potentially fixes also https://github.com/BlueWallet/BlueWallet/pull/4710
> Fix creating release notes for Android through Github Action

- App.js
- blue_modules/storage-context.js
- class/deeplink-schema-match.js
- ios/BlueWallet/Info.plist
- loc/en.json
- screen/wallets/addMultisigStep2.js
- screen/wallets/viewEditMultisigCosigners.js
- tests/unit/deeplink-schema-match.test.js
Introduces the feature to airdrop keys (Xpubs) during the MultiSig key creation phase. A lot less complexity than the [old PR](https://github.com/BlueWallet/BlueWallet/pull/5660).
> Reduced airdrop

- screen/wallets/transactions.js
a bit weird situation, i dunno how this even happened
> FIX: pull-to-refresh while inside the wallet doesnt update the tx list

- .github/workflows/ci.yml
> fix: separate test attempts

- components/AddressInput.js
- helpers/scan-qr.ts
- ios/Podfile
- ios/Podfile.lock
- package-lock.json
- package.json
- screen/lnd/lndCreateInvoice.js
- screen/send/ScanQRCode.js
- screen/send/details.js
- screen/send/isItMyAddress.js
- screen/send/psbtMultisigQRCode.js
- screen/send/psbtWithHardwareWallet.js
- screen/settings/electrumSettings.js
- screen/settings/lightningSettings.tsx
- screen/wallets/addMultisigStep2.js
- screen/wallets/import.js
- screen/wallets/list.js
- screen/wallets/transactions.js
- screen/wallets/viewEditMultisigCosigners.js
I'll refactor this later to have it just use the scanner helper instead of the separate request
> REF: Camera Authorization Request

- ios/BlueWallet/AppDelegate.mm
- ios/BlueWallet/Info.plist
- package-lock.json
As specified in:
https://github.com/software-mansion/react-native-screens/tree/main/native-stack#status-bar-and-orientation-managment
> FIX: View controller-based status bar appearance

- screen/wallets/list.js
Let the component figure it out
> FIX: The scrolling behavior after deleting a wallet was not natural.

- models/fiatUnit.ts
- models/fiatUnits.json
> FIX: #5619 Please add the Romanian Leu currency. Here’s how. #5619

- screen/ActionSheet.ios.js
- screen/ActionSheet.js
> FIX: Wait for transitions to finish before showing sheet

- blue_modules/storage-context.js
- components/TransactionsNavigationHeader.tsx
> ADD: See currency when tap and hold on balance

- scripts/remove-loc-key.sh
./scripts/remove-loc-key.sh invalid_animated_qr_code_fragment 
or
./scripts/remove-loc-key.sh entropy.save
> ADD: Script to remove a passed key from all locale JSON files

- blue_modules/analytics.js
supersedes https://github.com/BlueWallet/BlueWallet/pull/5752 but tries to achieve at in js-only way
> FIX: better tracking opt out (related #5688)

- screen/send/ScanQRCode.js
another case when updating RNnav went sideways.
e2e tests did not catch it because we dont actually broadcast txs
> FIX: exception trying broadcast after scanning PSBT from QR

- android/build.gradle
> FIX: Lower minsdk

- ios/BlueWallet.xcodeproj/project.pbxproj
- ios/fastlane/Fastfile
In order to debug on Apple physical devices you gotta register them. This automates the process by providing a txt file
> OPS: Device Registration Lane

- Navigation.js
- ios/BlueWallet/AppDelegate.mm
> FIX: Stack name warning

- ios/BlueWallet/BlueWallet.entitlements
- ios/BlueWallet/BlueWalletRelease.entitlements
- ios/BlueWallet/Info.plist
OS was expecting a string but found a boolean
> FIX: Startup crash on macOS app

- App.js
- ios/BlueWallet/AppDelegate.mm
- ios/EventEmitter.h
- ios/EventEmitter.m
> ADD: Add Wallet menu item

- android/app/src/main/AndroidManifest.xml
- blue_modules/fs.js
- blue_modules/fs.ts
- loc/en.json
- screen/selftest.js
Actual change is in the first commit, the second commit is converting to ts, cleanup, remove unused function
> Fix fs save and open android

- loc/en.json
- react-native.config.js
- screen/wallets/list.js
> ADD: Search for Wallet in Home screen (iOS)

- components/FloatButtons.tsx
> fix: use useSafeAreaInsets in FloatButtons component

- App.js
- UnlockWith.js
- WatchConnectivity.ios.js
- ios/BlueWallet-Bridging-Header.h
- ios/BlueWallet.xcodeproj/project.pbxproj
- ios/BlueWallet.xcodeproj/xcshareddata/xcschemes/BlueWallet.xcscheme
- ios/BlueWallet/AppDelegate.mm
- ios/SplashScreen.m
- ios/SplashScreen.swift
This should make sure the BW logo is displayed all the way through the Metro package bundler process. Android next
> FIX: Show iOS splash screen during bundler

- ios/BlueWallet-NoLDK.plist
- ios/BlueWallet/Info.plist
> ADD: Dont allow app to run if OS is unsupported

- components/WalletToImport.tsx
Don't mind if I submit a few more PRs like this, right?
> REF: WalletToImport to TS

- ios/BlueWallet.xcodeproj/project.pbxproj
- ios/fastlane/Fastfile
For certificates and provision profiles
> OPS: Add lanes for Catalyst

- components/SquareEnumeratedWords.tsx
Component to Typescript + removing inline styles
> REF: SquareEnumaratedWords to TS

- Navigation.tsx
- UnlockWith.tsx
- loc/en.json
- screen/UnlockWith.tsx
> ADD: Re-enable biometrics to unlock

- App.js
- package-lock.json
- screen/wallets/list.js
- screen/wallets/transactions.js
> FIX: Crash due to actionsheet changes

- ios/BlueWallet/AppDelegate.mm
appType can only be changed on the native side.
> ADD: Detect if report is from macOS

- components/TooltipMenu.android.js
- components/TransactionsNavigationHeader.tsx
- screen/transactions/details.js
The onPress was inconsistent if inside a child component on some android APIs
> REF: Use Pressable instead of TouchableOpacity for Android

- App.js
- components/HandOffComponent.ios.tsx
- components/HandOffComponent.tsx
- components/HandOffComponentListener.ios.tsx
- components/HandOffComponentListener.tsx
- screen/receive/details.js
- screen/transactions/details.js
- screen/transactions/transactionStatus.js
- screen/wallets/export.js
- screen/wallets/xpub.tsx
Dont bother on running in android. extract listener from app.js
> REF: Handoff component

- components/WalletsCarousel.js
> FIX: Carousel height was off on Android

- components/FloatButtons.tsx
- components/StyledButton.tsx
macOS:
https://github.com/BlueWallet/BlueWallet/assets/4793122/2b8f3822-176e-42ce-a5ee-9c36028aab90
iOS:
https://github.com/BlueWallet/BlueWallet/assets/4793122/9790aded-494f-47db-abd1-ed1e63acbc42
> ADD: Slide up animation for FloatButton

- components/FloatButtons.tsx
**Based on latest Figma design**
> REF: New button design

- screen/settings/Language.tsx
> FIX:  Languages row minimum height

- class/wallets/abstract-hd-electrum-wallet.ts
- class/wallets/legacy-wallet.ts
- class/wallets/multisig-hd-wallet.ts
- class/wallets/segwit-bech32-wallet.ts
- class/wallets/segwit-p2sh-wallet.ts
- class/wallets/types.ts
- tests/integration/bip47.test.ts
- tests/unit/bip47.test.ts
- tests/unit/hd-segwit-bech32-wallet.test.js
- typings/coinselect.d.ts
Preparing for a BIP-47 send feature, doing some refactorings to be able to send OP_RETURNs in transactions
@junderw can you pls take a look?
> ADD: technical release to be able to send outputs with custom scripts (OP_RETURNs in particular)

- class/bip39_wallet_formats.json
https://raw.githubusercontent.com/spesmilo/electrum/master/electrum/bip39_wallet_formats.json
> fix: sync bip39_wallet_formats.json with electrum source files

- Navigation.tsx
- screen/wallets/PleaseBackup.tsx
Also remove artificial loading as there's no need for it
> REF: mv pleasebackup

- class/wallets/abstract-hd-electrum-wallet.ts
- class/wallets/types.ts
- components/TransactionListItem.tsx
- loc/en.json
- screen/transactions/TransactionStatus.tsx
- tests/integration/bip47.test.ts
> Add display bip47 counterparty in tx list

- components/Context/SettingsContext.tsx
This allows all settings to process instead of being blocked from 1 failure
> REF: Use Promises instead of await

- loc/en.json
- screen/settings/SettingsPrivacy.tsx
It was not explained beforehand, making the feature’s disablement seem like a bug.
> ADD: Provide explanation for disabled feature

- ios/BlueWallet/AppDelegate.mm
- ios/Settings.bundle/Root.plist
This will make it easy to clear the cache.
> ADD: Settings > Clear Cache

- blue_modules/fs.ts
- components/AddressInput.tsx
- loc/en.json
press and hold to see menu so u dont have to load the scanner to access features
> ADD: Scan tooltip

- blue_modules/debounce.ts
- hooks/useDebounce.ts
- models/fiatUnit.ts
- models/fiatUnits.json
- screen/settings/Currency.tsx
> ADD: useDebounce hook

- components/AddressInput.tsx
- helpers/scan-qr.ts
- screen/send/Broadcast.tsx
- screen/send/details.tsx
- screen/send/psbtMultisigQRCode.js
- screen/settings/electrumSettings.js
- screen/wallets/ViewEditMultisigCosigners.tsx
- screen/wallets/WalletsList.tsx
- screen/wallets/addMultisigStep2.js
- screen/wallets/transactions.js
Closed previous PR as changing the parameter lead to chaos.
> REF: Use existing nav ref for scanQR helper #6601

- models/fiatUnits.json
- screen/settings/Currency.tsx
https://github.com/BlueWallet/BlueWallet/discussions/5221
> ADD: GHS and XAF

- class/wallets/abstract-hd-electrum-wallet.ts
- package-lock.json
- package.json
* simplified code a bit
* locked SP dep
> REF: silent-payments minor refactor

- class/wallet-import.ts
> fix: SLIP39 1-of-1

- ios/BlueWallet.xcodeproj/project.pbxproj
- ios/BlueWallet.xcodeproj/xcshareddata/xcschemes/WalletInformationWidget.xcscheme
- ios/Shared/MarketAPI+Electrum.swift
- ios/Shared/MarketAPI.swift
- ios/Shared/Utilities/Utilities.swift
- ios/WalletInformationWidget/WalletInformationWidget.swift
- ios/Widgets/WalletInformationAndMarketWidget/WalletInformationAndMarketWidget.swift
Widget now estimates fee using histogram
> REF: Fee estimation and price fetch improvement

- android/app/src/main/java/io/bluewallet/bluewallet/BitcoinPriceWidget.java
- android/app/src/main/res/layout/widget_layout.xml
- android/app/src/main/res/values-night/colors.xml
- android/app/src/main/res/values-night/styles.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/styles.xml
> ADD: Dark mode for Android price widget

- class/wallets/abstract-hd-electrum-wallet.ts
- class/wallets/legacy-wallet.ts
- components/FloatButtons.tsx
- loc/en.json
- navigation/LazyLoadAddWalletStack.tsx
- screen/wallets/Add.tsx
- screen/wallets/ProvideEntropy.tsx
- tests/unit/hd-segwit-p2sh-wallet.test.ts
- tests/unit/legacy-wallet.test.js
- tests/unit/provide-entropy.test.ts
- convert provideEntropy to typescript
- allow 12 or 24 words 
[entropy.webm](https://github.com/BlueWallet/BlueWallet/assets/155891/a7a25152-a347-4789-ae30-e7ddbec91e7f)
closes #6344
> feat: Entropy refactor

- class/blue-app.ts
- loc/en.json
- screen/send/SendDetails.tsx
- screen/wallets/PaymentCodesList.tsx
@marcosrdz i removed a couple of warnings as well, i dunno if you need them
> FIX: bip47 notif tx when inserting contact

- components/Header.tsx
- navigation/DetailViewScreensStack.tsx
- screen/settings/SettingsPrivacy.tsx
- screen/wallets/DrawerList.tsx
- screen/wallets/WalletsList.tsx
Im not a fan of this tbh.JS is single thread. The native approach is much better and "for free"
> REF: Animated scroll Header

- components/Header.tsx
- navigation/DetailViewScreensStack.tsx
- screen/settings/SettingsPrivacy.tsx
- screen/wallets/DrawerList.tsx
- screen/wallets/WalletsList.tsx
This reverts commit ce7a2b5211a97bcc9468c65fec038683e47174f6, reversing changes made to 204726d6b3448e775b1d4eda5006ca2917eb5880.
> Revert "Merge pull request #6718 from BlueWallet/h"

- ios/BlueWallet-NoLDK.plist
- ios/BlueWallet.xcodeproj/project.pbxproj
- ios/BlueWallet/Info.plist
- package.json
> DEL: Remove unused files

- loc/en.json
- screen/receive/details.js
> FIX: Create button in Custom amount was pointless

- package.json
- tests/e2e/bluewallet.spec.js
- tests/e2e/bluewallet2.spec.js
did some minor fixes, want to see if e2e will pass on a simple branch from master
> CI: refactor some tests

- package.json
- yarn.lock
@marcosrdz does this fix your issue
> fix: lock react-native-ios-context-menu with commit hash

- components/TransactionsNavigationHeader.tsx
- components/WalletsCarousel.tsx
Synchronous URL loading of http://localhost:8081/assets/img/vault-shape.png?platform=ios&hash=ec5b9afdbfc44fd87827c26d0bc9265d should not occur on this application's main thread as it may lead to UI unresponsiveness. Please switch to an asynchronous networking API such as URLSession.
Synchronous URL loading of http://localhost:8081/assets/img/btc-shape.png?platform=ios&hash=1b735986e8a6e62e3401aae99dff6f64 should not occur on this application's main thread as it may lead to UI unresponsiveness. Please switch to an asynchronous networking API such as URLSession.
> DEL: DefaultSource prop on Image

- screen/UnlockWith.tsx
Reverts BlueWallet/BlueWallet#7423
> Revert "Update UnlockWith.tsx"

- components/MultipleStepsListItem.js
- screen/wallets/ViewEditMultisigCosigners.tsx
Slower devices would appear to hang before modal showed up
> REF: Add loading indicator to Edit Vault row

- loc/en.json
- screen/wallets/Add.tsx
- screen/wallets/ProvideEntropy.tsx
Android alerts only allow max 3 buttons. This alert requires 4.
> REF: Entropy menu as Action instead of alert

- components/ManageWalletsListItem.tsx
> FIX: handle platform-specific icon compatibility for delete button

- .github/workflows/build-release-apk.yml
- fastlane/Fastfile
https://www.browserstack.com/support/faq/app-live/troubleshooting-app-live/how-to-resolve-the-upload-failed-app-is-blacklisted-error
> FIX: BS spam detection complaint

- components/FloatButtons.tsx
> ADD: Single button container should be round as per design

- class/wallets/abstract-hd-electrum-wallet.ts
It is possible that during fetchTransactions another function might change `this.next_free_address_index`
And this error might happen  
```
LOG  fetchWalletTransactions for wallet# 1
ERROR  [TypeError: Cannot read property 'filter' of undefined]
ERROR  Error in refreshAllWalletTransactions: [TypeError: Cannot read property 'filter' of undefined]
```
To avoid it, we shall cache `next_free_address_index` value
> fix: race condition error in HD wallet fetchTransactions

- blue_modules/BlueElectrum.ts
Changed null to undefined as macOS crashes on attempted unchecked access to null values (making the behavior across all systems the same)
> REF: Wrap BlueElecrum promises in try catch

- screen/send/ScanQRCode.tsx
- tests/e2e/bluewallet.spec.js
- tests/e2e/bluewallet2.spec.js
- tests/e2e/bluewallet3.spec.js
- tests/e2e/helperz.js
havent actually tested changes, but will. for now hope for e2e suite
> REF: scanQr to TS

- hooks/useHandoffListener.ios.ts
- ios/Podfile.lock
- package-lock.json
- package.json
Lower the file changes in Receive modal PR
> FIX: iOS runtime crash & update screens package

- .github/workflows/build-ios-release-pullrequest.yml
Xcode misbehaves sometimes when using cache
> OPS: Remove all cache when building from master.

- android/app/build.gradle
actually trying this trick:
https://x.com/margelo_io/status/1890789725872525381?s=67
> REF: improve startup time

- components/TooltipMenu.tsx
- components/addresses/AddressItem.tsx
- ios/BlueWallet.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package-lock.json
- package.json
- tests/setup.js
> DEL: ios-context package

- components/TransactionsNavigationHeader.tsx
- hooks/useExtendedNavigation.ts
- navigation/DetailViewScreensStack.tsx
- navigation/DetailViewStackParamList.ts
- navigation/ViewEditMultisigCosignersStack.tsx
- screen/wallets/ViewEditMultisigCosigners.tsx
- screen/wallets/WalletDetails.tsx
- screen/wallets/WalletTransactions.tsx
- tests/e2e/bluewallet2.spec.js
Reverts BlueWallet/BlueWallet#7631
> Revert "REF: Wallet tranaction header animation"

- hooks/useCompanionListeners.ts
- hooks/useMenuElements.ios.ts
- hooks/useMenuElements.ts
- ios/BlueWallet/AppDelegate.mm
- ios/MenuElementsEmitter/MenuElementsEmitter.swift
- screen/wallets/WalletTransactions.tsx
- screen/wallets/WalletsList.tsx
MenuItem has high memory consumption due to zombies
> REF: MenuItem memory

- screen/wallets/WalletTransactions.tsx
its not perfect..but its a step forward
> FIX: Pull-to-refresh glitch Iphone #7693

- ios/Widgets/Shared/SwiftTCPClient.swift
TCPClient (used for widgets) lacked proper connection retry and cancel. leading to zombies
> FIX: SwiftTCPClient connection management

- blue_modules/BlueElectrum.ts
- components/Context/StorageProvider.tsx
- package.json
- screen/wallets/WalletsList.tsx
- tests/e2e/bluewallet.spec.js
- tests/e2e/bluewallet2.spec.js
- tests/e2e/bluewallet3.spec.js
- tests/e2e/helperz.js
im thinking about  removing persistent electrum connection in favor of on-demand connection...
> FIX: electrum reconnect and refetch on app startup

- package-lock.json
- package.json
- tests/unit/segwit-bech32-wallet.test.js
Use coinselect from https://github.com/BlueWallet/coinselect where it is patched to allow decimal fee
> feat: decimal coinselect

- components/FloatButtons.tsx
- components/SafeAreaSectionList.tsx
- screen/wallets/WalletTransactions.tsx
- screen/wallets/WalletsList.tsx
> FIX: Float button calculation for large devices

- ios/Widgets/WalletAppShortcuts.swift
> FIX: iOS failed to compile

- components/HighlightedText.tsx
- components/ManageWalletsListItem.tsx
- components/TransactionListItem.tsx
- components/WalletsCarousel.tsx
- ios/Podfile.lock
- models/itemTypes.ts
- package-lock.json
- package.json
- screen/wallets/ManageWallets.tsx
> REF: Group wallet search results

- components/FloatButtons.tsx
- navigation/DetailViewScreensStack.tsx
- screen/wallets/DrawerList.tsx
- screen/wallets/WalletTransactions.tsx
same as https://github.com/BlueWallet/BlueWallet/pull/7857 just without jest config changes
> FIX: Receive screen

- fastlane/Fastfile
1. Enter manually..2. Clipboard....3. Release notes file
> OPS: Enhance update release notes to allow you to select method

- components/FloatButtons.tsx
- components/SegmentControl.android.tsx
This led to a crash to size calculation UI animation
> FIX: Natiive driver for Animations was wrongly set to false

- android/app/src/main/java/io/bluewallet/bluewallet/BitcoinPriceWidget.kt
- android/app/src/main/java/io/bluewallet/bluewallet/ElectrumClient.kt
- android/app/src/main/java/io/bluewallet/bluewallet/MainActivity.kt
- android/app/src/main/java/io/bluewallet/bluewallet/MarketAPI.kt
- android/app/src/main/java/io/bluewallet/bluewallet/MarketWidget.kt
- android/app/src/main/java/io/bluewallet/bluewallet/MarketWidgetUpdateWorker.kt
- android/app/src/main/java/io/bluewallet/bluewallet/WidgetUpdateWorker.kt
Fixes Google Play rejection (multiple instances were firing due to widget code)
> FIX: Widgets and main app should run in same instance

- class/deeplink-schema-match.ts
- scripts/deeplink-to-emusim.sh
> OPS: Enhance deeplink to emu script to list emulators booted

- hooks/useCompanionListeners.ts
- hooks/useOnAppLaunch.ts
- navigation/DrawerRoot.tsx
- navigation/MasterView.tsx
- screen/settings/DefaultView.tsx
> FIX: onapp launch was not working

- class/wallets/multisig-hd-wallet.ts
- screen/wallets/WalletAddresses.tsx
attempt to fix https://github.com/BlueWallet/BlueWallet/issues/7889
the root-cause is still unknown, but at least i added some guards (that might potentially solve it) and try-catches to prevent crashes and handle it gracefully.
> FIX: rare multisig crash (closes #7889)

- screen/wallets/WalletsList.tsx
- tests/e2e/bluewallet.spec.js
- tests/e2e/helperz.js
> FIX: can button on main screen

- components/AddWalletButton.tsx
- components/BottomModal.tsx
- components/Button.tsx
- components/MultipleStepsListItem.tsx
- components/WalletButton.tsx
- screen/send/SendDetails.tsx
- screen/wallets/MultisigAdvanced.tsx
- screen/wallets/WalletExport.tsx
This is a continuation from #7945  to replace TouchableOpacity with Pressable. Related to #2144
> Replace TouchableOpacity with Pressable (Part 2)

- blue_modules/noble_ecc.ts
- package-lock.json
- package.json
Replace `crypto.createHmac` with `@noble/hashes` for improved cross-platform compatibility and security.
> Add noble hashes dependency and refactor code
