BlueWallet/BlueWallet

screen/wallets/list.js, screen/wallets/transactions.js
Wallet name stays the same when changed in options and user has to manually refresh to get new name (as described in #27 ).
Since `react-navigation` keeps staked pages mounted, `componentDidMount` is called only after first render. We have to use `NavigationEvents` component which listens on `onWillFocus` event and calls the `refreshFunction` to get new data.
I'm not sure if this has any large drawbacks, but it is currently the only way to do it properly, the other being using Redux or other state container which would be the single source of truth.
I also removed `async` keywords which do nothing.
=> Refresh wallet info on page focus

screen/send/details.js
Current buggy behavior: 
- User sets fee using slider and closes modal with fee slider.
- Then decides to set fee again and opens fee modal
- Slider is set to the end even though value is lower
This fixed it
=> Fix: Fee slider not setting new value on change

App.js, android/app/src/main/AndroidManifest.xml, index.js, ios/BlueWallet/AppDelegate.m, ios/BlueWallet/Info.plist, screen/send/details.js
This is a work in progress to handle BIP21 (`bitcoin:`) deeplinks.
Current state is: clicked link opens the BlueWallet app, redirects to `SendDetails` page which opens the first wallet and parses amount+label and inserts into send form.
Desired state: Open app, open modal window with available wallets (only those able to send and only those with sufficient balance) and let user choose a wallet.
=> WIP: Handle BIP21 deeplinks

loc/en.js, loc/es.js, loc/pt_BR.js, loc/pt_PT.js, loc/ru.js, loc/ua.js, screen/transactions/details.js
I noticed (by accident) that in transaction detail, the TX ID is actually opens BlockCypher explorer. For a better UX, there needs to be a specific "Show in block explorer" link that user can see and use.
Before:
After:
=> Fix: Display proper link to block explorer

screen/wallets/reorderWallets.js, screen/wallets/selectWallet.js
This is something I stumbled upon: on "reorder wallets" screen and "choose wallet" screen, the Lightning wallet displays BTC as unit and not sats - as on the home screen.
This fixes it for now. I will create a separate reusable component for wallet item so these inconsistencies won't happen anymore.
=> Fix: Display wallet balance consistently on all screens

models/fiatUnit.js
hey BlueWallet team! First simple PR here. We're using your awesome wallet down in MX and we'd love to be able to see our balance in Mexican Peso. Let me know if you have any questions.
=> added Mexican Peso (MXN) as new fiatUnit

screen/wallets/list.js
without that animation starts and almost instantly terminates, while balance and txs are actually fetched in the background
=> FIX: wallets/list pull-to-refresh animation duration

.gitattributes
This fixes a problem with applying the patches
on Windows where the patch and the files to be
patched have different format for line endings.
=> Make patch files keep their line endings. Fix #429

App.js, screen/wallets/buyBitcoin.js
When the user buys bitcoin through Safello, they will be redirected to the Yoti app to verify their identity.
Previously, when the process was done, they would be redirected to a browser window to continue their purchase, but since bluewallet has a `bluewallet://` redirect URI associated to its
app ID, we can redirect them back to the app with a `safello-state-token` query parameter appended to the URI instead.
Bluewallet then simply needs to check if that query parameter is present, and if so, open a new WebView with the same Safello URL + `stateToken=xxx` in order to resume the user's session. This way, the whole buying process can take place inside Bluewallet's app, which is a clear improvement in terms of user experience.
What it looks like after the changes:
Note: You'll probably …
=> Support Safello redirect URLs

screen/lnd/lndViewInvoice.js
remove info icon, so it doesn't remove highlight and hierarchy from the important data, and leave aditional info as a secondary option
=> remove info icon

screen/receive/details.js
There was no space on small iPhones on the share button and the bottom of the device. This change allows the view grow naturally
=> fix lack of spacing in receive QR screen

package-lock.json, package.json
Related to https://github.com/BlueWallet/BlueWallet/issues/597
=> Lock bitcoinjs5 dependency to specific commit hash

loc/pt_PT.js
A lot of i18n files have an error on settings.lightning_settings_explain:
1. It ends with `'ndHub\n (lndhub.io)',`
2. The english version has one more sentence
I translated it from the english version.
=> fixes settings.lightning_settings_explain in loc/pt_PT.js

screen/wallets/details.js
Width of 40 was not sufficient for bigger words, and it was breaking (see screenshot):
Looking to all the translations of wallets.details.save, 120 seemed like a good choice for a new width value.
=> fixes bug where in pt_PT 'Save' ('Guardar') appears broken.

BlueComponents.js, class/lightning-custodian-wallet.js
Allow Hiding manage funds button since some lndhubs disable onchain address receive. leading to an empty receive UI.
=> ADD: Hide Manage Funds button if wallet doesn't allow onchain refill.

class/lightning-custodian-wallet.js, package.json, screen/lnd/scanLndInvoice.js, tests/integration/LightningCustodianWallet.test.js
This is a simple computation involving a small library that will save a roundtrip to the server every time a Lightning invoice is read.
If this is merged Lndhub's API can also deprecate the decode endpoint.
=> Decode Lightning invoices locally.

class/hd-legacy-electrum-seed-p2pkh-wallet.js, package-lock.json, package.json
Note: This can be a potentially breaking change in the following scenario:
1. User creates segwit wallet in Electrum.
2. User imports the seed into BlueWallet.
3. BlueWallet will use the seed to generate a legacy wallet when the seed's version prefix is not legacy.
4. Patched version will suddenly break it for them.
TBH I think the number of users using this is small enough to just patch it and help them out when they create an issue.
=> Fix Electrum recovery bug

package-lock.json, package.json
Fixes:
```
npm ERR! code 128
npm ERR! Command failed: git checkout 38332f629f577cdd57c69fc8cc971b3cbad193c9
npm ERR! fatal: reference is not a tree: 38332f629f577cdd57c69fc8cc971b3cbad193c9
npm ERR!
```
Looks like the specified commit for `marcosrdz/react-native-secure-key-store` has been removed and now it can't be resolved.
I've done a quick check and the updated tip of master commit appears to still work ok. Not super familiar with how it's used though so would be good for someone more familiar to confirm.
=> Fix npm install

class/legacy-wallet.js, tests/integration/legacy-wallet.test.js
Was unable to view transactions for the following bitcoin address without this fix - [1PVfrmbn1vSMoFZB2Ga7nDuXLFDyJZHrHK](https://www.blockchain.com/btc/address/1PVfrmbn1vSMoFZB2Ga7nDuXLFDyJZHrHK)
=> FIX: for legacy-wallet.fetchTransactions() to not crash when vout for transaction is missing addresses.

BlueElectrum.js, class/legacy-wallet.js, tests/integration/legacy-wallet.test.js
This batchsize change allowed me to retrieve transactions for the following 2 wallet addresses without receiving an undefined exception.
34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo
18rnfoQgGo1HqvVQaAN4QnxjYE7Sez9eca
=> FIX: Reduced batchsize to prevent "undefined" error when retrieving transactions

BlueComponents.js
in BlueComponents.js
https://github.com/BlueWallet/BlueWallet/issues/1073
=> fix typo 'Have your saved' => 'Have you saved'

package-lock.json, package.json
Fixing #905 
upgraded frisbee version from v2.0.9 to v3.1.2
- tests work
- checked lightning network screen
- checked hodlhodl screen
Everything works fine
=> FIX: bump frisbee package to 3.1.2

package.json
This will make tests fail much faster if there are any problems with linter
=> REF: run eslint before any other tests

android/app/build.gradle, currency.js, index.js, package-lock.json, package.json, tests/integration/Currency.test.js, tests/unit/Currency.test.js
In my lightning wallet I have transactions with very small amounts, like 1 Satoshi.
When I'm switching wallet to show values in USD it shows me transaction amount of *$0.00*
I've changed `Currency.satoshiToLocalCurrency` function so: 
if value is more than 1, it renders 2  digits after decimal point.
1.123 -> 1.12
If value less than 1, it renders 2 significant digits after decimal point
0.123 -> 0.12
0.00000567 -> 0.0000057
More examples at [tests](https://github.com/BlueWallet/BlueWallet/commit/f120bc95fbcbef3985334c35f684e3da8c9e5e67#diff-6d0d8e8ba20fdcb5559fec2003df241a) 
Because current version uses `Intl` polyfill which doesn't supports modern `Intl.NumberFormat` API, I've removed it and used `Intl` wich comes with react-native. Starting 0.60 it comes with it
=> FIX: round fiat currencies to 2 significant digits

Navigation.js, screen/wallets/reorderWallets.js, screen/wallets/selectWallet.js
On the iOS you can close modal by pull down gesture.
It already works in BlueWallet on scanQRCore, import and other modals, but only if you grab them by Header. 
I'm extending grab area to the full height of the modals.
Unfortunately it doesn't work everywhere correctly. That's why I'm disabling gestures for reorderWallets and selectWallet screens.
On android gestures are disabled by default, so it is not affected. 
I'm only changing gestureResponseDistance.vertical, horizontal remains default - 50
It feels very cool on import or scanqrcode screens
=> ADD: extend pull to close gesture area to full modal height

Navigation.js, class/deeplink-schema-match.js, screen/wallets/selectWallet.js, tests/unit/deeplink-schema-match.test.js
Originally Success screen was 2 levels deep and when `navigation.dangerouslyGetParent().pop()` was called in it, it didn't close the SelectWallet screen.
I've fixed it by dismissing SelectWallet after wallet is selected.
Also I've discovered that all screen that are needed for this workflow to works are already exists inside RootStack. So I've removed HandleOffchainAndOnChain completely to simplify the code.
Less code - better!
=> FIX: following onchain+offchain invoice

class/wallets/abstract-wallet.js, tests/unit/watch-only-wallet.test.js
Bitcoin Core uses an HD key format with maser fingerprint and derivation path in square brackets:
`[fingerprint/derivation]xpub`
In [Specter](https://github.com/cryptoadvance/specter-diy) we use a similar way to display xpubs. This PR adds support for this format of xpub and fills the master fingerprint.
=> Add support for zpub with fingerprint

README.md, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, package-lock.json
Solves the issue described [here](https://stackoverflow.com/questions/60844245/how-solve-could-not-initialize-class-org-codehaus-groovy-reflection-reflectionc).
I encountered this while attempting to build and run the latest master locally on MacOS using the latest version of Android Studio (4.0.1).
=> OPS: Update gradle settings and versions.

BlueComponents.js
When wallet is watch-only we need to show one button - Receive and it should take all the space in floatButtons container
Before:
After
=> FIX: recieve button for watch-only wallets

blue_modules/BlueElectrum.js, class/app-storage.js, package-lock.json, package.json
I researched on all available databases for RN and chose realm for now, because its not sql-based (its document oriented) and built in encryption
so I rewrote storing data, and heavy data is now offloaded to realm, so we are not encrypting megabytes of data in JS process, it is offloaded to native realm process where it is encrypted and then flushed to disk
so, wallet with 1k txs taking 10MB now works very well, our saveToDisk() procedure takes 1sec max
we call saveToDisk every time some data changed, like, if we fetched new txs from electrum
bad news: realm here is used in a goofy way. because realm requires strict schema definition, and we have very complex internal representation of transactions (tree-like) and it differs from wallet type to wallet type
so heavy transaction data is …
=> ref-storage-in-realm-db

loc/en.json
Changed
"A wallet represents a pair of a secret (private key) and an addressyou can share to receive coins"
to
"A wallet represents a pair of keys, one private and one you can share to receive coins"
=> FIX: Improve wallet description translation

screen/wallets/transactions.js
- each render of `WalletTransactions` creates new interval
- in `setInterval` the state is changing which triggers render
- after a few cycles we have hundreds re-renders each of them triggers `wallet.getTransactions`
- app freezes
I've moved interval creation to `useEffect`, now it will be executed only once on component mount.
=> FIX: create interval for tx list in useEffect hook

BlueComponents.js
Fixing #1801
change textAlign from right to left
=> FIX: textAlign: left for custom fee in CPFP/RBF form

screen/wallets/transactions.js
Because BlueTransactionListItem is a pure component we need to change timeElapsed to force it render
=> FIX: change TimeElapsed on transactions refresh to force items render

BlueComponents.js, loc/en.json, screen/send/details.js, screen/wallets/transactions.js
Trying to reduce deepscan warnings
* useMemo/useCallback in `BlueTransactionListItem` to render `BlueListItem` as a pure component
* change `conf: <number>` locale string so left-to-right languages look better
* useFocusEffect in wallet/transactions to re-render items after description change
=> REF: remove a few Deepscan errors

class/wallet-import.js, loc/en.json, screen/wallets/import.js
In this PR I tried to improve the subjective speed of wallet import:
* camera should close instantly as soon as QR is read
* operations like closing camera, adding placeholder wallet, are moved one level up & added sleeps to give animations 
& UI some time to re-render
* simplified a bit
=> REF: improve wallet import speed

screen/wallets/transactions.js
Padding is causing text being concealed by the Receive/Send buttons like this:
I removed the padding from the text container `scrollViewContent` to save some space and contain the text:
Of course you can fix it decreasing the font size, or make it scroll-able.
It's also [affect](https://user-images.githubusercontent.com/4103710/96641540-8a51ba00-132d-11eb-9eb1-030d6ee140da.png) the bitcoin [transactions screen](https://user-images.githubusercontent.com/4103710/96641534-89208d00-132d-11eb-8dce-f09deb9778fb.png), but I think it's not critical.
=> FIX: remove padding causing text concealment

BlueComponents.js, loc/en.json
#2013
It fails because in `loc.transactions.details.copy` `loc.transactions.details` was undefined
I've also translated Show/Hide balance strings
=> FIX: copy balance on wallet/transactions screen

class/deeplink-schema-match.js, class/lnurl.js, screen/lnd/lndCreateInvoice.js, tests/unit/lnurl.test.js
There was partial support mixed in with the code but it didn't work actually.
This PR also uses the `Lnurl` class to replace some old code in the lnurl-withdraw handler.
=> support lnurl fallback scheme.

components/BottomModal.js, screen/receive/details.js, screen/send/details.js, screen/send/psbtMultisig.js, screen/wallets/addMultisig.js, screen/wallets/addMultisigStep2.js, screen/wallets/hodlHodl.js, screen/wallets/hodlHodlMyContracts.js, screen/wallets/transactions.js, screen/wallets/viewEditMultisigCosigners.js
Because `react-native-modal` is used in BW only for bottom modals it shares a lot of common logic. Like getting window height/width or duplication of onBackButtonPress/onBackdropPress. So I've moved this common logic to a separate component.
=> REF: BottomModal component

class/wallets/hd-legacy-breadwallet-wallet.js, tests/integration/hd-legacy-breadwallet.test.js, tests/unit/hd-legacy-breadwallet.test.js
At some point in BRD started to generate bech32 change addresses.  It is also possible to enable segwit for a wallet and it will generate bech32 addresses for incoming transactions.
Idea of this patch find index where wallet was switched to segwit and alter address generation scheme.
* During initial scan in `fetchBlance()` find derive path (index) at which BRD was switched to segwit. For external and internal addresses
* save these indexes to `_external_segwit_index` and `_internal_segwit_index`
* `_getExternalAddressByIndex` will return legacy address if index < than `_external_segwit_index` and Bech32 if not. Same for `_getInternalAddressByIndex`. This will make them backward compatible. 
I was able to recover balance and tx history of my BRD wallet using this branch.
Question: 
* …
=> FIX: BRD wallet with segwit

screen/wallets/transactions.js
Freshly imported wallets has positive balance and no transactions in a list. 
This patch adds `refreshTransactions` call if this happens.
=> ADD: refresh wallet transactions for freshly imported wallets

class/wallets/legacy-wallet.js
curious side-effect of contextifying everything.  fetchTransactions for single-addresses started with cleaning up internal variable, and BW would remove them from screen if you open single-address wallet too fast after launch
cc @limpbrains @marcosrdz
=> FIX: txs disappear and re-fetch if opened wallet too fast

loc/en.json, screen/wallets/addMultisig.js
fixed so only 2-3 will show that text. others will render:
=> FIX: contradiction in Vaul introduction text (closes #2327)

class/wallets/legacy-wallet.js, class/wallets/multisig-hd-wallet.js, screen/send/details.js
When the user tries to send more funds than a wallet balance, BW still tries to precalculate fee to show something. 
To do this all transaction output values was replaced with dust value. In result, this tx always smaller than maximum possible option, because it has smaller number of inputs. 
Now BW will create tx with the same amount of outputs, but one of them will be MAX. It will allow showing more accurate fee estimation.
Fixes #2404
=> FIX: show more accurate precalculation fee on "Not enough balance." exception

loc/index.js
When switching back to English, dayjs wouldnt change.
=> FIX: Fallback to English if case isn't found

class/wallets/multisig-hd-wallet.js, loc/en.json, screen/wallets/addMultisigStep2.js, screen/wallets/viewEditMultisigCosigners.js
in this  PR we add new features to 'manage keys' multisig screen, in particular, user can now press 'share' on keys and get a QR or a file for the specific cosigner, in case he wants to import them somewhere else (specter or other BW).
its a bit ugly but its the easiest place I could place it, plus its gonna be a rarely used feature:
ALSO, in this PR we forbid usage of regular HD wallets xpubs when creating multisig (for example, zpub from BIP84 wallet)
=> Fix multisig

class/wallets/multisig-hd-wallet.js
`wallet.getUtxo(true)` must be used, cause otherwise it will return a limited UTXO set
=> FIX: multisig coin control

BlueComponents.js, components/WalletsCarousel.js
For some reason content of <Text> in RN disappears of it switches from left-to-right to right-to-left text.
By adding `key` to the Text I'm forcing it recreation on balance change.
closes #2592
=> FIX: BlueWalletNavigationHeader force balance remount on unit change

App.js, screen/lnd/lndCreateInvoice.js, screen/receive/details.js, screen/send/broadcast.js, screen/send/coinControl.js, screen/send/details.js, screen/send/isItMyAddress.js, screen/transactions/CPFP.js, screen/wallets/addMultisig.js, screen/wallets/addMultisigStep2.js, screen/wallets/details.js, screen/wallets/hodlHodl.js, screen/wallets/hodlHodlMyContracts.js, screen/wallets/hodlHodlViewOffer.js, screen/wallets/transactions.js, screen/wallets/viewEditMultisigCosigners.js
iPadOS offers floating keyboard. KeyboardAvoidingView breaks when this is in use. Currently theres no RN API  to detect when keyboard is in floating mode. Since iPads have large displays, the content shouldnt be covered by the keyboard.
=> FIX:  Custom fee cancelation on iPadOS 14.4 fade into black screen #2568

components/WalletsCarousel.js, tests/e2e/bluewallet.spec.js
When I'm rutting e2e tests I have about 10-20% failed results because of import errors. Import fails because of connection problems, like
```
[Fri Feb 26 2021 13:22:40.100]  LOG      posting analytics... GOT_ZERO_BALANCE
[Fri Feb 26 2021 13:22:50.652]  LOG      reconnecting after socket error
[Fri Feb 26 2021 13:22:55.690]  WARN     [Error: Connection to server lost, please retry]
[Fri Feb 26 2021 13:23:07.220]  WARN     [Error: Connection to server lost, please retry]
[Fri Feb 26 2021 13:23:23.924]  WARN     [Error: Connection to server lost, please retry]
[Fri Feb 26 2021 13:23:23.929]  WARN     [Error: Connection to server lost, please retry]
[Fri Feb 26 2021 13:23:32.274]  LOG      [Error: Connection to server lost, please retry]
[Fri Feb 26 2021 13:23:32.371]  LOG      begin …
```
=> TST: retry helperImportWallet

class/wallet-gradient.js, components/WalletsCarousel.js
Cards colors haven't been optimized since we first released them. 
This includes:
- More color contrast, better on dark mode
- Default wallet color as the light blue (hopefully not a big change to scare users, let me know if you noticed it)
https://user-images.githubusercontent.com/1238429/110954994-6711c080-8349-11eb-8937-8e11f0f4c80b.mov
=> REF: Wallets cards colors optimized

screen/send/create.js, screen/send/success.js
=> FIX: avoid scientific notation on tx send screens

UnlockWith.js
Removes the big image (legacy) and adds the animation in static mode from the previous screen
=> REF: Add loading image to unlock screen

tests/integration/import.test.js
- `can import BIP49` test is duplicated:
https://github.com/BlueWallet/BlueWallet/blob/bab13a1b0242afba71c224d10c0f6bbd30ed57cf/tests/integration/import.test.js#L105-L121
- (nit) remove this comment:
https://github.com/BlueWallet/BlueWallet/blob/bab13a1b0242afba71c224d10c0f6bbd30ed57cf/tests/integration/import.test.js#L88
=> TST: Remove duplicated test

screen/send/coinControl.js
Use `numberOfLines={1} ellipsizeMode="middle"` to truncate load addresses in the middle. 
This way text fills all available space.
Before
After
=> REF: coincontrol truncate addresses middle

screen/wallets/transactions.js
Since #2851 it is possible to have freshly imported wallet with 0 balance and no transactions.
We want to automatically start refreshing when the user opens this wallet. 
So instead of checking for positive balance, lest check wallet last tx fetch time
=> REF: refresh wallet if it never been done

screen/receive/details.js
Looks like `newAddress` should be checked for `undefined`, not `address`.
related to #2976
=> FIX: recieve/details screen typo

BlueComponents.js, UnlockWith.js, blue_modules/BlueElectrum.js, class/wallets/abstract-hd-electrum-wallet.js, class/wallets/legacy-wallet.js, class/wallets/watch-only-wallet.js, screen/send/details.js, screen/send/psbtWithHardwareWallet.js, screen/wallets/addMultisigHelp.js, tests/setup.js
in this PR we introduce a long-overdue electrum cache for `multiGetTransactionByTxid` call.
only transactions with >7 confirmations are cached.
this should greatly improve network fetch for batched transactions: sometimes exchange withdrawals have _thousands_ of inputs, and our code has to fetch each one of them to correctly calculate input amounts and thus, transaction value. they are now cached and repeated wallet refresh will take less time (in my case for my wallet, from 100 sec to 3 sec).
cache resides in a separate realm database file.
=> Electrum cache

.github/workflows/codeql-analysis.yml
=> Remove git checkout HEAD^2 in the CodeQL check

class/wallets/hd-segwit-electrum-seed-p2wpkh-wallet.js, tests/unit/hd-segwit-electrum-seed-p2wpkh-wallet.test.js
Right now BW shows incorrect Xpub for bech32 electrum wallets. I've fixed it, and now it shows correct Zpub.
closes #2941
=> ADD: show zpub for electrum seed segwit wallets

blue_modules/WidgetCommunication.android.js, blue_modules/analytics.js, blue_modules/storage-context.js, class/app-storage.js, ios/Podfile.lock, loc/en.json, package-lock.json, package.json, screen/settings/SettingsPrivacy.js
added a switch in settings/general/privacy to disable tracking.
should prevent sending data to amplitude & sentry.
@marcosrdz pay attention to how I used context, I might have done it wrong
=> ADD: opt-out of analytics tracking in settings/privacy (rel #3084)

BlueApp.js, blue_modules/BlueElectrum.js, blue_modules/currency.js, blue_modules/storage-context.js, class/app-storage.js, class/biometrics.js, loc/index.js, screen/settings/electrumSettings.js, tests/integration/Currency.test.js, tests/setup.js
long story short, we have this issue with random storage drop: https://github.com/BlueWallet/BlueWallet/issues/3177
in attempt to fix it, we will try to use less secure keystore and more asyncstorage.
we have this AppStorage singleton, which was supposed to handle all data persisnce when bw was created, but in retrospective it was a bad idea:
there were no advantages in keeping data management centralized (and all we do is simple key-value anyway), and all surrounding code turned into legacy mess.
probably a better approach is to let each piece of functionality (like a separate module like currency) to handle its data on its own.
so in this PR we are trying to achieve exactly that: 
1) some keys constants moved where they make more sense 
2) three storage keys that used to be stored in …
=> REF: storage improvements

class/wallet-import.js
Disable `wallet.wasEverUsed()` check for bech32 slip39 wallets. So BW will import bech32 wallet for fresh seed.
closes #3297
=> FIX: for slip39 wallets import bech32 even if no tx found

index.js
https://github.com/software-mansion/react-native-screens/issues/1017
RNScreens v3 enabled screens by default resulting in slow behavior on low end android devices. Previous versions required devs to manually enable it. Disabling for now until issue is resolved.
=> FIX: Disable enable screens

loc/en.json
Make this message more explicit and in particular that the wallets already created are not impacted by the change of the parameter (and that a new wallet must therefore be created if we want to use these new parameters).  Keyword: **only**.
Found this out after updating this parameter and wondering why I could still receive payments while my node hadn't got any active channel yet =)
=> REF: Reformulate helping text

ios/BlueWallet.xcodeproj/project.pbxproj, ios/Podfile.lock, scripts/maccatalystpatches/applypatchesformaccatalyst.sh
Builds would get release notes from old commits rather than the latest ones
=> FIX: Remove existing release notes when applying Catalyst patches.

class/wallets/legacy-wallet.ts
```
im looking into that  huge address from user
it has 4k transactions
no way its gona fetch transactions in adequate time
im thinking about throwing an exception in case single address has more that, i dunno, 1k transactions..?
the rest should work fine - balance will update, and txs can be created (given that user uses normal electrum server, that suppots listUtxo call, unlike EPS that doesnt support that and we rely on deriving utxo from existing stored transactions)
```
=> REF: dont load address txs if > 1000

BlueComponents.js, screen/transactions/details.js
There were an error on transactions/details screen
Because styles where joining with object destruction. It doesn't work if your style is an array.
I switched to StyleSheet.compose and removed a couple of duplicate styles
```js 
Warning: Failed prop type: Invalid props.style key `0` supplied to `Text`.
Bad object: {
"0": {
"fontSize": 16,
"fontWeight": "500"
},
"1": {
"color": "#0c2550"
},
"color": "#0c2550",
"writingDirection": "ltr"
}
Valid keys: [
"display",
"width",
"height",
"start",
...
]
at Text
in TextElement (at withTheme.js:44)
in Themed.Text (at BlueComponents.js:386)
in BlueText (at details.js:193)
in RCTView (at View.js:34)
in View (at details.js:192)
in RCTView (at View.js:34)
in View (at BlueComponents.js:380)
in BlueCard (at details.js:151)
in RCTScrollContentView (at …
```
=> FIX: styles on transactions/details screen

scripts/release-notes.sh
fix #3145
If run release-notes.sh from master, it will show notes staring from last tag.
But if you checkout specific tag, it will show notes starting from the previous tag to the current one
cc @emanuelb
=> FIX: generate release notes if running from tag checkout

class/app-storage.js, tests/unit/storage.test.js
a bit risky change. we change format of storing HD wallets transactions in realm. before, we json encoded all txs in a single json blob and wrote it in a single realm row.
that started failing when some users transactions exceeded 30 mb.
after that change we store 1 tx per row, so we now practically can store unlimited amount of transactions (again HD wallets only).
after the update, users will notice transactions disappearing and then re-fetching.
also, if user updated to this build its impossible to go back, as realm doesn't allow schema downgrade.
cc @ncoelho
=> Fix 3357 txs in realm

BlueComponents.js, loc/en.json
if you drastically change loc string in en.json and it now has different meaning, it is better to create new key for it. Otherwise it should be deleted from all other loc files.
related to #3810
=> FIX: vByte in loc

class/wallet-import.js
wallet.getID() is enought, because it is already contains hash of secret + passphrase
closes #3848
@mcsaeid please test it
=> FIX: do not check secret when adding new wallet

class/app-storage.js
Basically same as #3849
- If you add 2 wallets with same seed, but different passphrase, and try to remove one wallet, both wallets will be removed
- same for loading from disk. one wallet will be removed if they both have same seed
PS
We use getID() quite often in the app. And it always calculates sha256, for it. How fast is it? Should we optimize it? Switch to constant id's, for example. Of cache it.
=> FIX: use getID to compare wallets during delete and loadFromDisk

models/fiatUnits.json, tests/integration/Currency.test.js
The correct Iranian currency is IRT or Iranian Toman. Exir* also shows the amount in toman instead of rial (IRR).
Since IRR is one-tenth of an IRT, the amount shown in BlueWallet is incorrect. It should be ten times more†. People rarely use IRR in daily life, anyway.
*‌ https://github.com/BlueWallet/BlueWallet/blob/42be5c9b56f371ee2ce9109bdab6a98ecdd08f46/models/fiatUnit.ts#L62
† The correct amount shown in the screenshot should have been ۱۵۱٬۹۷۷٬۵۰۰٫۰۰ ﷼.
**Question**
How can we fix the thousands separators? They look off. For comparison, look at the Persian numbers above. I am also using the Arabic Thousands Separator (U+066C) instead of a comma.
=> FIX: Iranian currency

screen/lnd/scanLndInvoice.js
`walletID` is not set when user scans code on main screen
closes #3679
=> FIX: refresh lndhub wallet balance after paying for invoice by scanning qrcode on main screen

screen/wallets/list.js
Right now pull-to-refresh is broken on main screen, because instead of calling `refreshAllWalletTransactions(` with index of wallet to refresh it was called with `true`
=> FIX: Pull-to-refresh on main screen

blue_modules/ur/index.js, screen/send/ScanQRCode.js
In this case AirGap shows BC-UR CRYPTO-ACCOUNT animated Qr-code. But blue_modules/ur/index.js decodeUR func can't handle multipart qr-code. Instead of waiting for more data it raises empty error. That is why I've changed handler for `UR:CRYPTO-ACCOUNT` from old `_onReadUniformResource` to new `_onReadUniformResourceV2` which uses `BlueURDecoder` class. 
Also I've extended `BlueURDecoder` to be able to work with CRYPTO-ACCOUNT. 
Looks like BC-UR handling in BW needs to be refactored.
closes #4229
=> FIX: scan BC-UR Crypto-Account animated

components/AmountInput.js, loc/en.json, screen/lnd/lndCreateInvoice.js
I removed  auto-formatting, which was supper annoying, and replaced it with form on submit validation.
https://user-images.githubusercontent.com/155891/153920624-3533569a-b055-4552-ba5e-de967ebf0121.mp4
Also super-nice log in `AmountInput.js`that looks like this:
`100000000(sats) -> 100000000(sats) -> 42723.25(local_currency)`
one line, instead of 3
`AmountInput.js` is a true mess and deserves refactoring alongside with loc/format and `currencies.js`
closes #4471
=> FIX: min/max in lndCreateInvoice

screen/lnd/lndCreateInvoice.js
=> FIX: lnurl-withdrawal bug when it says 'Maximum amount is X  sats'

components/AmountInput.js
I regularly use BlueWallet to reserve hotels/flights using Bitcoin transactions (0.0.....1231 BTC), and I had problems with 1-9 satoshis missing because of the too short text editor input size. It's very frustrating, but this change will probably fix the bug.
=> Be able to send exact amount in BTC

class/wallets/abstract-wallet.ts, tests/unit/fixtures/skeleton-electrum-hex-only.txt, tests/unit/watch-only-wallet.test.js
fixes #4641  in event that root_fingerprint is a hex value. does reverse of what Number().toString() does by using parseInt() with radix.
=> fixed failing import

android/app/src/main/res/xml/network_security_config.xml, ios/BlueWallet/Info.plist
#4852 
Would allow [Tailscale](https://community.getumbrel.com/t/how-to-use-umbrel-with-tailscale/6782) users to use ["MagicDNS"](https://tailscale.com/kb/1081/magicdns/) URIs as their LNDHub connection URI.  Tailscale is just a zero-config fireguard VPN, so these connections are already encrypted and require authentication and authorization.
=> allow tailscale to connect using "MagicDNS" over HTTP

models/fiatUnits.json
=> ADD: Fiat Unit - Uganda Shilling UGX

ios/Podfile.lock, screen/wallets/export.js
Apps that show super sensitive information dismiss the modal containing said info when the app is sent to background. Such as Settings > Passwords in iOS and some bank apps.
=> ADD: Dismiss Export screen if app was sent to background

android/app/build.gradle, android/build.gradle, loc/en.json, package-lock.json, package.json, screen/send/ScanQRCode.js
switched to new camera dep: https://github.com/teslamotors/react-native-camera-kit
unfortunately still uses google deps, but at least its maintained, so should not block upgrade to RN70.
also, code is pretty clear so I might be able to fork it and reimplement actual QR detection on the image.
also i like it way more than vision-camera which feels overengineered
=> REF: switchet camera dependency (unfortunately still uses google libs)

ios/BlueWallet/Info.plist
Howdy!
Tailscale's [MagicDNS](https://tailscale.com/kb/1081/magicdns/) service now utilises a new [Tailnet](https://tailscale.com/kb/1217/tailnet-name/) naming scheme which ends in `ts.net`
Tailscale's MagicDNS was whitelisted previously in #4854 - `beta.tailscale.net` remains supported until Nov 1, 2023 after which all users will need to migrate to the new Tailnet naming scheme.
=> ADD: Tailscale's new Tailnet naming scheme to list of exceptions

models/fiatUnits.json
Use Yadio instead of coindesk for correct Chilean Peso market price.
I'm not too familiar with the code so I hope I'm not missing something here.
I see Yadio has two types of results:
YadioConvert:
https://github.com/BlueWallet/BlueWallet/blob/9d8a6356e5fca4ec98e575322394442d280ffa0b/models/fiatUnit.ts#L44
and Yadio:
https://github.com/BlueWallet/BlueWallet/blob/9d8a6356e5fca4ec98e575322394442d280ffa0b/models/fiatUnit.ts#L28
This PR uses the latter, but price is  a little different using the former. In any case the price is far more accurate than coindesk
=> change CLP price provider

screen/lnd/lnurlPaySuccess.js, screen/send/success.js
Resolves #2893
The text after making a payment extends across the screen.
Add a new style to the container and set horizontal padding.
I also checked that the `SuccessView` was introducing some unwanted spaces, I have refactored it so that it only takes up the necessary space.
<div>
</div>
<div>
</div>
I have checked that the other screens which use the `SuccessView` component are not broken after the change.
<div>
</div>
=> fix(styles): adjust spaces on the success view

components/TooltipMenu.ios.js
If u pressed a tx list item really quickly after long press the onPress would trigger both the navigation and menu show which would lead to a crash
=> FIX: Cleanup the menu when the view is navigating away

class/app-storage.js, class/wallets/abstract-hd-electrum-wallet.ts, package-lock.json, package.json, screen/wallets/details.js, screen/wallets/transactions.js
* forked bip47 dep under our org
* refactored a bit to speed it up
* if payment codes are disabled, wallets wont even try to fetch their balance from network
=> REF: hide bip47 behind backdoor; refactor

class/wallets/abstract-hd-electrum-wallet.ts, class/wallets/hd-legacy-electrum-seed-p2pkh-wallet.js, class/wallets/hd-segwit-electrum-seed-p2wpkh-wallet.js, class/wallets/slip39-wallets.js, loc/en.json, screen/wallets/paymentCode.tsx, tests/integration/import.test.js
- add missing localization
- disable bip47 for SLIP39 and Electrum Seed wallets, until proper tested
- when importing seed from the BIP47 wallet 
- both BIP84 and BIP44 wallets will be offered for import, if transactions for notification address is discovered
=> Bip47 improvements

components/WalletsCarousel.js, screen/wallets/drawerList.js, screen/wallets/list.js
This will open the door to future features that will prefer the item instead of index. Such as search.
Don't decide when to render NewWallet or CarouseItem before return.
=> REF: Pass item rather than index

screen/send/confirm.js
fix #5313 
PayjoinClient requires named `opts.wallet`, we passed `opts.payJoinWallet` before
=> Satisfy PayjoinClient wallet param

screen/wallets/details.js
Summary of changes 
Enable exportation of wallet history. transactions to be done by both on-chain and off-chain
=> Enable lightning(offchain) wallet transactions to be exported to csv

screen/wallets/addMultisigStep2.js
=> fix: round circles on Multisig screen

Navigation.js, blue_modules/checksumWords.js, loc/en.json, screen/settings/tools.js, screen/wallets/generateWord.js, tests/unit/checksumWords.test.js
=> ADD: tool to generate last mnemonic word

components/AddressInput.js
Perhaps you have the qr code in a private drive or a third party app (like Proton)
=> ADD: Allow importing a QR Code image from other sources

class/lnurl.js
https://twitter.com/callebtc/status/1752643575274152281
https://github.com/lnurl/luds/pull/234
=> FIX: remove the LNURLp metadata validation

screen/send/broadcast.js
If you go to **Settings -> Tools -> Broadcast transaction** and press on the **Scan or import file** button, nothing happens. The helper function for scanning QR codes changed to a named export on [#5737](https://github.com/BlueWallet/BlueWallet/pull/5737/files#diff-7772257044ad461701957c3a7542ee19127dbdb5f5de60d04f9a0f47607532edL11) and this screen wasn't updated with the new name.
=> FIX: Scan button on Broadcast tool

.github/workflows/build-ios-release-pullrequest.yml, .github/workflows/build-ios-release-testflight.yml
macos-latest doesnt include the release of xcode that includes required SDK releases
=> OPS: Change runner to more recent xcode releases

screen/settings/Currency.tsx
=> FIX: Currency row height issue on some devices

components/TooltipMenu.ios.js, components/addresses/AddressItem.tsx
Require cycle: components/QRCodeComponent.tsx -> components/TooltipMenu.ios.js -> components/QRCodeComponent.tsx
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
=> REF: Component cycle

ios/BlueWallet.xcodeproj/xcshareddata/xcschemes/BlueWallet-NoLDK.xcscheme, loc/en.json, screen/wallets/viewEditMultisigCosigners.tsx
If user tries to exit, or accidentally presses back then allow them to confirm.
=> ADD: Discard changes prompt

metro.config.js
> node node_modules/react-native/local-cli/cli.js start --reset-cache
warn From React Native 0.72, your metro.config.js file should extend'@react-native/metro-config'. Please see the React Native 0.72 changelog, or copy the template at:
https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn Falling back to internal defaults.
This PR updates the metro config file to comply with the changes
=> FIX: Metro warning

components/WalletsCarousel.js
WARN  (ADVICE) View #199 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.
WARN  (ADVICE) View #163 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.
WARN  (ADVICE) View #125 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.
LinearGradient shouldn't draw shadows.
=> FIX:  Wallet shadow set to wrong view

class/wallets/multisig-hd-wallet.ts, screen/wallets/ViewEditMultisigCosigners.tsx, screen/wallets/addMultisigStep2.js, tests/unit/multisig-hd-wallet.test.js
* Passphrases werenr taken into account when offering to share cosigners xpubs
* incorrect xpubs were taken when deriving addresses in multisig when  cosigners have same seeds BUT different passphrases (cosigners were looked up by seed)
=> FIX: errors when working with multisig seeds with passphrases 

components/ListItem.tsx, components/TransactionListItem.tsx
I modified some styles so that the Bitcoin quantity in the transaction list does not wrap even when the text size is increased in the iPhone settings.  
Below screenshots are captured on iPhone 13 Mini with maximized text size setting.
|  master branch | this PR  |
|---|---|
|  ![Simulator Screenshot - iPhone 13 mini - 2024-05-07 at 02 33 16](https://github.com/BlueWallet/BlueWallet/assets/5436405/1dd5316b-150d-4961-9e47-c29006c713dc) | ![Simulator Screenshot - iPhone 13 mini - 2024-05-07 at 02 30 42](https://github.com/BlueWallet/BlueWallet/assets/5436405/833ef77d-8e55-424c-a7b2-cfe9eabb88e8) |
=> FIX: Make value text grow on TransactionListItem.

components/TransactionListItem.tsx, loc/index.ts, navigation/SendDetailsStack.tsx, screen/settings/EncryptStorage.tsx, screen/wallets/WalletsList.tsx
Helps easily find mistakes in using localization strings.
```
❯ npx tsc
screen/wallets/WalletsList.tsx:362:32 - error TS2339: Property 'WRONG_STRING_ID' does not exist on type '{ add_bitcoin: string; add_bitcoin_explain: string; add_create: string; add_entropy_generated: string; add_entropy_provide: string; add_entropy_remain: string; add_import_wallet: string; ... 86 more ...; search_wallets: string; }'.
362       options.push(loc.wallets.WRONG_STRING_ID);
~~~~~~~~~~~~~~~
Found 1 error in screen/wallets/WalletsList.tsx:362
```
=> fix: TS localization vocabulary

class/wallets/slip39-wallets.ts, package-lock.json, package.json, typings/slip39.d.ts
React native now has native BigInt support. We don't have to maintain our slip39-js fork anymore.
Also new version now includes "extendable backup flag" feature
closes #6603
=> fix: upgrade slip39 dependency

.circleci/config.yml, .github/workflows/ci.yml, package-lock.json, package.json, tests/custom-environment.js, tests/custom-reporter.js
I experimented with built-in `jest.retryTimes(1);` but it didnt really work for me, probably because it retries testcases but does not re-run `beforeAll` to setup electrum connection (which is often the cause of a failed test)
so instead i coded similar mechanism we have for e2e:
each green test  writes a lock file in /tmp (this happens in new custom jest reporter), and then test suite is rerun,
and previously passed  tests are skipped (this happens in a custom jest environment)
=> TST: add retries for integration tests on CI

package-lock.json
temporarily used `overrides` field in package to bump it and fixate in a lock file
=> REF: bumped transient dependency elliptic to close a vuln

loc/en.json
This pull request corrects the improper use of the indefinite article "an" before the word "universal" in the payment codes description. While "universal" begins with the orthographic vowel "u," its phonetic onset /juː-/ includes a semi-vowel /j/, making "a" the grammatically correct article.
Replaced "an" with "a" in the following string:
`Payment codes are an universal address that avoids disclosing your wallet addresses.`
Now reads:
`Payment codes are a universal address that avoids disclosing your wallet addresses.`
=> Fix improper article usage before "universal" in payment codes description.

helpers/scan-qr.ts, index.js, navigation/DetailViewStackParamList.ts, screen/send/Broadcast.tsx, screen/send/ScanQRCode.tsx, screen/settings/IsItMyAddress.tsx
looked up rnav docs, apparently passing a callback in navigation params is ok unless you need to deeplink to said screen, or want to save nav state to disk or smth...
https://reactnavigation.org/docs/troubleshooting/#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state
@marcosrdz what can be problematic in the future in this setup? 
also refactored 2 screens to use this helper, got rid of useEffect fuckery which is very unobvious;  and theres more deletions than additionsin those screens
=> refactor: bring back scan qr helper

components/TransactionListItem.tsx, screen/wallets/WalletDetails.tsx, screen/wallets/WalletTransactions.tsx, tests/e2e/bluewallet2.spec.js, tests/e2e/bluewallet3.spec.js, tests/e2e/helperz.js
not sure if i made it correctly,  looks like we have excessive caching on transactions list screen, useMemo inside useCallback inside useMemo etc etc
so i added extra dep in useEffect so that cached tx list is re-calculated.
most importantly, i wrote an e2e test that purges wallet data, pulls-to-refresh and checks that data got pulled
=> FIX: transactions list screen would not always update with new transactions

screen/send/SendDetails.tsx
Small optimization. We don't need to re-calculate targets each time inside the loop
=> fix: on SendDetails screen move targets creation out of options loop

components/Context/LargeScreenProvider.tsx, components/DevMenu.tsx, hooks/useIsLargeScreen.ts, ios/BlueWallet/AppDelegate.mm, ios/BlueWallet/Info.plist, navigation/index.tsx, screen/wallets/Add.tsx
Standard iOS behavior we werent allowing
=> REF: Allow large screen iPhone devices to use same UI as iPad/macSO

.circleci/config.yml, .github/workflows/build-ios-release-pullrequest.yml, .github/workflows/build-release-apk.yml, .github/workflows/ci.yml, .github/workflows/lockfiles_update.yml, package-lock.json
switched from `npm install` to `npm ci` 
simplified npm caches
added omit-dev deps for e2e pipeline
=> OPS: improve CI

class/wallet-import.ts, class/wallets/taproot-wallet.ts, class/wallets/types.ts, tests/unit/taproot-wallet.test.ts
Adding support for taproot single-address wallets. 
this is first step towards supporting BIP86 (full HD taproot wallets) and SilentPayments receive.
@limpbrains im not sure if i correctly addred it to import procedure
(havent tested the PR in actual app)
=> ADD: single-address Taproot wallets support (import from WIF)

hooks/useWalletSubscribe.tsx, screen/wallets/WalletTransactions.tsx
We have an ongoing problem with React hook dependencies. Since our `Wallet` class is not designed with reactivity in mind, we can't use it as a dependency—it does not mutate.
For example:
```ts
const wallet = wallets.find(w => w.getID() === walletID);
useMemo(() => {
return wallet.getTransactions();
}, [wallet]);
```
This will never update when the wallet has new transactions.
With this hook you can do:
```ts
const wallet = useWallet(walletID);
useMemo(() => {
return wallet.getTransactions();
}, [wallet]);
```
And it will update the tx list.
I've tested it with `WalletTransactions` screen.
**The downside** of this approach is that all `useEffect` hooks will now trigger whenever the wallet is updated, so we need to be careful about this.
It is possible to use this hook when you need to …
=> feat: useWalletSubscribe hook

BlueComponents.js, components/themes.ts, screen/settings/About.tsx, screen/settings/IsItMyAddress.tsx
This PR begins the migration from TouchableOpacity to Pressable, as discussed https://github.com/BlueWallet/BlueWallet/issues/2144#issuecomment-2962365350. Additional PRs will follow to complete the migration
Replaced TouchableOpacity with Pressable in:
- `BlueComponents.js`
- `screen/settings/About.tsx`
- `screen/settings/IsItMyAddress.tsx`
Buttons with background:
- Applied `android_ripple` feedback on Android (color: "#ccc").
- Applied `opacity: 0.6` on iOS when pressed.
Text-only pressables:
- Used `opacity: 0.6` on both platforms for a consistent visual press effect.
This is a scoped update to a few files to verify if the implementation meets expectations.
Happy to iterate based on feedback before continuing with the broader migration.
Related to: #2144
=> REF: Replace TouchableOpacity with Pressable ( part 1 )

hooks/useExtendedNavigation.ts, screen/wallets/WalletDetails.tsx
Fixes: #7839
This PR addresses the issue where users are not able to delete multiple wallets without restarting the app
This fix uses `CommonActions.reset()` to:
- Clear the entire navigation stack
- Redirect users to `WalletsList`
- Prevent back navigation to screens associated with deleted data
I also tested `StackActions.replace()` but opted for `reset()` for a more consistent navigation state.
Let me know if you would prefer a different approach or if any changes are needed, happy to adjust.
=> FIX: Unable to delete multiple wallets without restarting

package-lock.json, package.json
Remove direct `ecurve` dependency.
The `ecurve` dependency was removed from direct dependencies. It remains as a transitive dependency through `bip38` (github.com/BlueWallet/bip38.git).
=> Remove ecurve dependency

class/wallets/lightning-custodian-wallet.ts
Fix `getLatestTransactionTime()` to return `0` when no transactions exist, resolving type mismatch and pull-to-refresh issues.
=> Fix return type for latest transaction time

loc/en.json, screen/SelectFeeScreen.tsx, screen/send/SendDetails.tsx
Fixes #7964
This PR removes the restriction that prevented users from entering custom transaction fee rates below 1 sat/vB
=> ADD: Allow custom fees below 1 sat/vByte

loc/index.ts, tests/unit/loc.test.js
When user enters a custom fee below 1 sat/vByte, the fee was being calculated and displayed in exponent form eg 1.5e-7 BTC
This PR fixes that bug and displays the amount in decimals eg 0.00000015 BTC
=> FIX: Custom fee displayed in exponent form (eg 1.5e-7)

ios/BlueWallet/Info.plist
Added accurate `NSFaceIDUsageDescription` that fulfills the requirement of ["A message that tells people why the app is requesting the ability to authenticate with Face ID"](https://developer.apple.com/documentation/bundleresources/information-property-list/nsfaceidusagedescription) rather than restating the system popup. 
Removed App Transport Security redundancy. (The value of `NSAllowsArbitraryLoads` is [ignored](https://developer.apple.com/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads) in the presence of `NSAllowsLocalNetworking`)
=> Info.plist: fixed NSFaceIDUsageDescription & removed ATS redundancy

blue_modules/BlueElectrum.ts
Went offline a while ago due to this bug in CPython. https://github.com/spesmilo/electrumx/issues/92#issuecomment-841822489
Has been running well since applying the linked patch. Also updated to newer domain name.
=> Re enable @lukechilds electrum server

android/app/src/main/assets/fiatUnits.json, ios/Widgets/Shared/FiatUnitEnum.swift, models/fiatUnits.json
This PR introduces support for the **Egyptian Pound (EGP)** as a fiat currency across Android, iOS, and shared models.
* **fiatUnits.json** (Android & models):
* Added `EGP` entry with ISO code, locale (`ar-EG`), symbol (`ج.م.`), and country.
* Configured source as **YadioConverter**.
* **FiatUnitEnum (iOS)**:
* Added `EGP` case with source `YadioConvert`.
* Added display representation: `"Egypt (Egyptian Pound)"`.
Closes #8077
=> ADD: add Egyptian Pound (EGP) support using yadioConverter

models/fiatUnit.ts, models/fiatUnits.json
Switched the fiat rate source from `CoinDesk` to `Coinbase` for several currencies.
- `CoinDesk` does not provide BTC exchange rates for most of these currencies.
- For UGX and ISK, `CoinDesk` returns a fixed value that does not reflect the real market rate.
Updated the source for the following currencies:
- AMD (Armenian Dram)
- AWG (Aruban Florin)
- HRK (Croatian Kuna)
- ISK (Icelandic Króna)
- MZN (Mozambican Metical)
- OMR (Omani Rial)
- PYG (Paraguayan Guarani)
- QAR (Qatari Riyal)
- RSD (Serbian Dinar)
- TZS (Tanzanian Shilling)
- UGX (Ugandan Shilling)
- UYU (Uruguayan Peso)
- XAF (Central African Franc)
- GHS (Ghanaian Cedi)
=> FIX: handle missing or invalid CoinDesk rates for certain currencies
